import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };
export type JsonObject = { [key: string]: JsonValue };
export function object(value: unknown, context: string): JsonObject {
  if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error(`${context}: expected an object.`);
  return value as JsonObject;
}
export function strings(value: unknown, context: string): string[] {
  if (!Array.isArray(value) || value.some((entry) => typeof entry !== "string")) throw new Error(`${context}: expected string values.`);
  return value;
}
export function string(value: unknown, context: string): string {
  if (typeof value !== "string" || !value) throw new Error(`${context}: expected a nonempty string.`);
  return value;
}
export type MetadataInput = { path: string; kind: "xml" | "toml" | "setup" | "csv"; text: string };
export function parseMetadata(records: MetadataInput[]): Map<string, JsonObject | JsonValue[]> {
  const result = spawnSync("python", [fileURLToPath(new URL("./parse_metadata.py", import.meta.url))], {
    input: JSON.stringify(records), encoding: "utf8", maxBuffer: 64 * 1024 * 1024,
  });
  if (result.error) throw new Error("Python 3.11+ is required for static package-metadata decoding.", { cause: result.error });
  if (result.status !== 0) throw new Error(`Static metadata decoding failed: ${result.stderr.trim()}`);
  const decoded: unknown = JSON.parse(result.stdout);
  if (!Array.isArray(decoded) || decoded.length !== records.length) throw new Error("Incomplete static metadata result.");
  const values = new Map<string, JsonObject | JsonValue[]>();
  for (const entry of decoded) {
    const record = object(entry, "Metadata result");
    const path = string(record.path, "Metadata path");
    if (values.has(path)) throw new Error(`Duplicate metadata result: ${path}.`);
    values.set(path, Array.isArray(record.value) ? record.value : object(record.value, path));
  }
  return values;
}
export function globMatch(value: string, pattern: string, separator = "/"): boolean {
  let expression = "^";
  for (let index = 0; index < pattern.length; index++) {
    const character = pattern[index];
    if (character === "*" && pattern[index + 1] === "*") {
      if (pattern[index + 2] === separator) { expression += `(?:.*${separator})?`; index += 2; }
      else { expression += ".*"; index++; }
    } else if (character === "*") expression += separator === "." ? ".*" : "[^/]*";
    else if (character === "?") expression += separator === "." ? "." : "[^/]";
    else expression += character.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
  return new RegExp(expression + "$").test(value);
}
export function generatorHeader(text: string, language: "java" | "python"): boolean {
  const lines: string[] = [];
  let block = false;
  for (const row of text.replace(/^\uFEFF/, "").split(/\r\n|\r|\n/)) {
    const trimmed = row.trimStart();
    if (!trimmed) continue;
    if (language === "python") {
      if (!trimmed.startsWith("#")) break;
      lines.push(trimmed);
    } else if (block || trimmed.startsWith("/*")) {
      lines.push(trimmed);
      block = !trimmed.includes("*/");
      if (!block && trimmed.slice(trimmed.indexOf("*/") + 2).trim()) break;
    } else if (trimmed.startsWith("//")) lines.push(trimmed);
    else break;
  }
  return /Code generated by Microsoft \(R\) (?:AutoRest|TypeSpec|Python) Code Generator\b/i.test(lines.join("\n"));
}
