version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/tools/sdk-testgen/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  
  - package-ecosystem: "npm"
    directory: "/eng/common/tsp-client"
    schedule:
      interval: daily
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/eng/common/spelling"
    schedule:
      interval: daily

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
