using './main.bicep'

param location = readEnvironmentVariable('AZURE_AI_LOCATION', readEnvironmentVariable('AZURE_LOCATION', 'westus2'))
param managedIdentityPrincipalId = readEnvironmentVariable('MANAGED_IDENTITY_PRINCIPAL_ID', '')
param searchServicePrincipalId = readEnvironmentVariable('SEARCH_SERVICE_PRINCIPAL_ID', '')
param storageAccountName = readEnvironmentVariable('STORAGE_ACCOUNT_NAME', '')
param storageBlobEndpoint = readEnvironmentVariable('STORAGE_BLOB_ENDPOINT', '')
param containerRegistryName = readEnvironmentVariable('CONTAINER_REGISTRY_NAME', '')
param developerGroupObjectId = readEnvironmentVariable('DEVELOPER_PRINCIPAL_ID', '')
param developerPrincipalType = readEnvironmentVariable('DEVELOPER_PRINCIPAL_TYPE', 'User')
param deploymentPrincipalObjectId = readEnvironmentVariable('DEPLOYMENT_PRINCIPAL_ID', '')
param deploymentPrincipalType = readEnvironmentVariable('DEPLOYMENT_PRINCIPAL_TYPE', 'ServicePrincipal')
param manageAuthorizationResources = readEnvironmentVariable('MANAGE_AUTHORIZATION_RESOURCES', 'true') == 'true'
param aiResourceNameOverride = readEnvironmentVariable('AI_RESOURCE_NAME_OVERRIDE', '')
param restoreAiResource = readEnvironmentVariable('AI_RESOURCE_RESTORE', 'false') == 'true'
param aiProjectNameOverride = readEnvironmentVariable('AI_PROJECT_NAME_OVERRIDE', '')
param agentLogWorkspaceNameOverride = readEnvironmentVariable('AGENT_LOG_WORKSPACE_NAME', '')
param agentLogWorkspaceLocation = readEnvironmentVariable('AGENT_LOG_WORKSPACE_LOCATION', readEnvironmentVariable('AZURE_AI_LOCATION', readEnvironmentVariable('AZURE_LOCATION', 'westus2')))
param agentAppInsightsNameOverride = readEnvironmentVariable('AGENT_APP_INSIGHTS_NAME', '')
param aiResourceUserAssignedIdentities = json(readEnvironmentVariable('AI_RESOURCE_USER_ASSIGNED_IDENTITIES', '{}'))
param agentLogRetentionInDays = int(readEnvironmentVariable('AGENT_LOG_RETENTION_IN_DAYS', '30'))
param modelRaiPolicyName = readEnvironmentVariable('MODEL_RAI_POLICY_NAME', 'Microsoft.DefaultV2')
param gpt41SkuName = readEnvironmentVariable('GPT_4_1_SKU_NAME', 'GlobalStandard')
param gpt41Capacity = int(readEnvironmentVariable('GPT_4_1_CAPACITY', '1'))
param gpt56SolCapacity = int(readEnvironmentVariable('GPT_5_6_SOL_CAPACITY', '500'))
param gpt51Capacity = int(readEnvironmentVariable('GPT_5_1_CAPACITY', '1'))
param gpt5MiniCapacity = int(readEnvironmentVariable('GPT_5_MINI_CAPACITY', '1'))
param textEmbedding3SmallCapacity = int(readEnvironmentVariable('TEXT_EMBEDDING_3_SMALL_CAPACITY', '1'))
param textEmbedding3SmallVersionUpgradeOption = readEnvironmentVariable('TEXT_EMBEDDING_3_SMALL_VERSION_UPGRADE_OPTION', 'NoAutoUpgrade')
