name: tools - sdk-ai-bots-agent-server - provision-and-deploy

trigger: none
pr: none

parameters:
    - name: environment
      type: string
      default: dev
      values: [dev, preview, prod]

variables:
    - template: /eng/pipelines/templates/variables/globals.yml
    - template: /eng/pipelines/templates/variables/image.yml

extends:
    template: /eng/pipelines/templates/stages/1es-redirect.yml
    parameters:
        Use1ESOfficial: true
        stages:
            - template: /tools/sdk-ai-bots/deployment/pipelines/templates/provision-and-deploy-component.yml
              parameters:
                  component: agent-server
                  dependencyLayers: resource-group,shared-resources,agent,frontend
                  environment: ${{ parameters.environment }}
