ARG ARCH=
FROM mcr.microsoft.com/dotnet/sdk:6.0.102-alpine3.14${ARCH} AS build

# copy the code
COPY docker_build/Azure.Sdk.Tools.TestProxy/ /proxyservercode

# publish the package
RUN cd /proxyservercode && dotnet publish -c Release -o /proxyserver -f net6.0

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine3.14${ARCH}

ENV \
    NO_AT_BRIDGE=1 \
    CERT_FOLDER=/var/certwork \
    CERT_IMPORT_SH=apply-dev-cert.sh \
    ASPNETCORE_ENVIRONMENT=Development \
    # this override allows the tool server to listen to traffic over the docker bridge.
    # default URL of localhost:5000 or localhost:50001 are not usable from outside the container
    ASPNETCORE_URLS="http://0.0.0.0:5000;https://0.0.0.0:5001" \
    Logging__Console__FormatterName= \
    Logging__LogLevel__Default=Information \
    Logging__LogLevel__Microsoft=Information \
    TEST_PROXY_FOLDER="/srv/testproxy/" \
    PATH="/proxyserver:${PATH}" \
    TEST_PROXY_CONTAINER=true

# dotnet-dev-certs tool is not included in aspnet image, so manually copy from sdk image
COPY --from=build /usr/share/dotnet/sdk/6.0.102/DotnetTools/dotnet-dev-certs/6.0.2-servicing.22064.12/tools/net6.0/any/ /dotnet-dev-certs

# prep the machine dev certificate
COPY docker_build/$CERT_IMPORT_SH docker_build/dotnet-devcert.pfx docker_build/dotnet-devcert.crt $CERT_FOLDER/
ADD run_proxy.sh /proxyserver/test-proxy

RUN \
    apk add --no-cache bash nss-tools openssh git \
    # Fix line endings
    && sed -i -e 's/\r$//' $CERT_FOLDER/$CERT_IMPORT_SH \
    && sed -i -e 's/\r$//' /proxyserver/test-proxy \
    # Use copied dotnet-dev-certs tool
    && sed -i -e 's|dotnet dev-certs|dotnet /dotnet-dev-certs/dotnet-dev-certs.dll|' $CERT_FOLDER/$CERT_IMPORT_SH \
    # Run script to import certificate
    && chmod +x $CERT_FOLDER/$CERT_IMPORT_SH \
    && chmod +x /proxyserver/test-proxy \
    && $CERT_FOLDER/$CERT_IMPORT_SH \
    && rm $CERT_FOLDER/$CERT_IMPORT_SH \
    && mkdir -p /srv/testproxy

EXPOSE 5000 5001

WORKDIR /proxyserver

COPY --from=build /proxyserver .

CMD ["test-proxy", "start", "--dump"]
