FROM mcr.microsoft.com/dotnet/sdk:5.0.303-nanoserver-1809 AS build_env

# copy the code
COPY docker_build/Azure.Sdk.Tools.TestProxy/ /proxyservercode

# publish the package
RUN cd /proxyservercode && dotnet publish -c Release -o /proxyserver -f net5.0

FROM mcr.microsoft.com/dotnet/aspnet:5.0.3-nanoserver-1809 AS build

# Copy PowerShell Core from the installer container
ENV ProgramFiles="C:\Program Files" \
    # set a fixed location for the Module analysis cache
    PSModuleAnalysisCachePath="C:\Users\Public\AppData\Local\Microsoft\Windows\PowerShell\docker\ModuleAnalysisCache" \
    # Persist %PSCORE% ENV variable for user convenience
    PSCORE="$ProgramFiles\PowerShell\pwsh.exe" \
    # Set the default windows path so we can use it
    WindowsPATH="C:\Windows\system32;C:\Windows" \
    NO_AT_BRIDGE=1 \
    ASPNETCORE_ENVIRONMENT=Development \
    # these environment variables are workarounds for the inability to "trust" a certificate due to permissions issues on the windows platform
    # we would obviously prefer to use...
    # RUN dotnet dev-certs https --trust
    # ...to trust the cert we imported above. However, due to the fact that a UI is REQUIRED to assent to this specific tool, 
    # it won't work on docker. ADDITIONALLY, we can't use the methodology of using powershell to insert into the LocalMachine/Root
    # as even if we surround it in a USER ContainerAdministrator to elevate our access, we STILL hit weird permission denied errors 
    # and he ASP.NET startup still can't load it as a dev certificate. 
    ASPNETCORE_Kestrel__Certificates__Default__Path="/certwork/dotnet-devcert.pfx" \
    ASPNETCORE_Kestrel__Certificates__Default__Password="password"  \
    # this override allows the tool server to listen to traffic over the docker bridge.
    # default URL of localhost:5000 or localhost:50001 are not usable from outside the container
    ASPNETCORE_URLS="http://0.0.0.0:5000;https://0.0.0.0:5001"
    
# while it may seem a bit strange to use "etc" on a windows container. We are mirroring
# the methodology from the primary container, which is linux.
RUN mkdir certwork & mkdir etc & cd etc & mkdir testproxy
ADD docker_build/dotnet-devcert.pfx certwork

WORKDIR /proxyserver

COPY --from=build_env /proxyserver .

EXPOSE 5001
EXPOSE 5000

ENTRYPOINT ["dotnet", "Azure.Sdk.Tools.TestProxy.dll", "--storage-location", "/etc/testproxy"]
