using System.Collections.Generic;
using System.Linq;
using Azure.Sdk.Tools.CodeownersMigration.Verification;
using Azure.Sdk.Tools.CodeownersUtils.Parsing;
using NUnit.Framework;

namespace Azure.Sdk.Tools.CodeownersMigration.Tests
{
    /// <summary>
    /// A defect in the comparer is worse than no comparison at all, because it produces a false assurance
    /// that ownership was preserved. The tests are therefore split into the two directions of failure: no
    /// false positives (formatting noise must not be reported) and no false negatives (every semantic
    /// change must be reported).
    ///
    /// All fixtures use plain '@user' owners so that nothing here depends on the team expansion blob, which
    /// keeps the suite runnable offline and in CI.
    /// </summary>
    public class EntryComparerTests
    {
        private static List<CodeownersEntry> Parse(params string[] lines)
        {
            return CodeownersParser.ParseCodeownersEntries(lines.ToList());
        }

        private static List<EntryDifference> Compare(string[] baseLines, string[] compareLines)
        {
            return new EntryComparer().Compare(Parse(baseLines), Parse(compareLines));
        }

        #region No false positives

        [Test]
        public void IdenticalFilesAreEquivalent()
        {
            string[] file =
            {
                "# PRLabel: %Tables",
                "/sdk/tables/    @alice @bob",
                "",
                "# ServiceLabel: %Storage",
                "# ServiceOwners: @carol"
            };

            Assert.That(Compare(file, file), Is.Empty);
        }

        [Test]
        public void CommentsAndBlankLinesAreIgnored()
        {
            string[] baseLines =
            {
                "# This is a hand-written banner",
                "###########",
                "# Section  #",
                "###########",
                "",
                "# PRLabel: %Tables",
                "/sdk/tables/    @alice @bob"
            };

            string[] compareLines =
            {
                "# Generated by tooling. Do not edit.",
                "",
                "",
                "# PRLabel: %Tables",
                "/sdk/tables/    @alice @bob"
            };

            Assert.That(Compare(baseLines, compareLines), Is.Empty);
        }

        [Test]
        public void OwnerOrderWithinAnEntryIsIgnored()
        {
            string[] baseLines = { "/sdk/tables/    @alice @bob" };
            string[] compareLines = { "/sdk/tables/    @bob @alice" };

            Assert.That(Compare(baseLines, compareLines), Is.Empty);
        }

        [Test]
        public void OwnerCaseAndWhitespaceAreIgnored()
        {
            string[] baseLines = { "/sdk/tables/    @Alice @BOB" };
            string[] compareLines = { "/sdk/tables/        @alice     @bob" };

            Assert.That(Compare(baseLines, compareLines), Is.Empty);
        }

        [Test]
        public void InheritedOwnersMatchTheirExplicitForm()
        {
            // A block ending in a source path line makes the source owners the service owners implicitly.
            string[] baseLines =
            {
                "# ServiceLabel: %Storage",
                "/sdk/storage/    @carol"
            };

            Assert.That(Compare(baseLines, baseLines), Is.Empty);

            List<EntryFacts> facts = Parse(baseLines).Select(EntryFacts.FromEntry).ToList();
            Assert.That(facts[0].ServiceOwners, Is.EqualTo(new[] { "carol" }),
                "The parser's implicit inheritance must be re-applied, otherwise service ownership is compared as empty on both sides and any change to it passes unnoticed.");
        }

        #endregion

        #region No false negatives

        [Test]
        public void ChangedSourceOwnerIsReported()
        {
            string[] baseLines = { "/sdk/tables/    @alice @bob" };
            string[] compareLines = { "/sdk/tables/    @alice @carol" };

            List<EntryDifference> differences = Compare(baseLines, compareLines);

            Assert.That(differences, Has.Count.EqualTo(1));
            Assert.That(differences[0].Kind, Is.EqualTo(DifferenceKind.FieldChanged));
            Assert.That(differences[0].Field, Is.EqualTo("SourceOwners"));
        }

        [Test]
        public void RemovedOwnerIsReported()
        {
            string[] baseLines = { "/sdk/tables/    @alice @bob" };
            string[] compareLines = { "/sdk/tables/    @alice" };

            Assert.That(Compare(baseLines, compareLines).Select(d => d.Field), Is.EqualTo(new[] { "SourceOwners" }));
        }

        [Test]
        public void ChangedPathIsReported()
        {
            string[] baseLines = { "/sdk/tables/    @alice" };
            string[] compareLines = { "/sdk/storage/    @alice" };

            Assert.That(Compare(baseLines, compareLines).Select(d => d.Field), Is.EqualTo(new[] { "PathExpression" }));
        }

        [Test]
        public void TrailingSlashChangeIsReported()
        {
            // '/sdk/tables' and '/sdk/tables/' select different files in GitHub's matcher, so this is a real
            // ownership change and must not be normalized away.
            string[] baseLines = { "/sdk/tables    @alice" };
            string[] compareLines = { "/sdk/tables/    @alice" };

            Assert.That(Compare(baseLines, compareLines).Select(d => d.Field), Is.EqualTo(new[] { "PathExpression" }));
        }

        [Test]
        public void ChangedPRLabelIsReported()
        {
            string[] baseLines = { "# PRLabel: %Tables", "/sdk/tables/    @alice" };
            string[] compareLines = { "# PRLabel: %Storage", "/sdk/tables/    @alice" };

            Assert.That(Compare(baseLines, compareLines).Select(d => d.Field), Is.EqualTo(new[] { "PRLabels" }));
        }

        [Test]
        public void ChangedServiceLabelIsReported()
        {
            string[] baseLines = { "# ServiceLabel: %Storage", "# ServiceOwners: @carol" };
            string[] compareLines = { "# ServiceLabel: %Tables", "# ServiceOwners: @carol" };

            Assert.That(Compare(baseLines, compareLines).Select(d => d.Field), Is.EqualTo(new[] { "ServiceLabels" }));
        }

        [Test]
        public void ChangedServiceOwnerIsReported()
        {
            string[] baseLines = { "# ServiceLabel: %Storage", "# ServiceOwners: @carol" };
            string[] compareLines = { "# ServiceLabel: %Storage", "# ServiceOwners: @dave" };

            Assert.That(Compare(baseLines, compareLines).Select(d => d.Field), Is.EqualTo(new[] { "ServiceOwners" }));
        }

        [Test]
        public void ChangedAzureSdkOwnerIsReported()
        {
            string[] baseLines = { "# AzureSdkOwners: @alice", "# ServiceLabel: %Storage", "# ServiceOwners: @carol" };
            string[] compareLines = { "# AzureSdkOwners: @bob", "# ServiceLabel: %Storage", "# ServiceOwners: @carol" };

            Assert.That(Compare(baseLines, compareLines).Select(d => d.Field), Is.EqualTo(new[] { "AzureSdkOwners" }));
        }

        [Test]
        public void DroppingInheritedServiceOwnersIsReported()
        {
            // The inheriting shorthand carries service owners; writing the label on its own block does not.
            // This is the regression that would silently strip service ownership.
            string[] baseLines = { "# ServiceLabel: %Storage", "/sdk/storage/    @carol" };
            string[] compareLines = { "# ServiceLabel: %Storage", "# ServiceOwners: @carol", "", "/sdk/storage/    @carol" };

            Assert.That(Compare(baseLines, compareLines), Is.Not.Empty);
        }

        [Test]
        public void ReorderedEntriesAreReported()
        {
            // Resolution is last-match-wins, so identical entries in a different order own different files.
            // A set-based comparison would call these equal; the ordinal comparison must not.
            string[] baseLines = { "/sdk/a/    @alice", "/sdk/b/    @bob" };
            string[] compareLines = { "/sdk/b/    @bob", "/sdk/a/    @alice" };

            List<EntryDifference> differences = Compare(baseLines, compareLines);

            Assert.That(differences, Is.Not.Empty);
            Assert.That(differences.All(d => d.Kind == DifferenceKind.FieldChanged), Is.True);
        }

        [Test]
        public void EntryMissingFromCompareIsReported()
        {
            string[] baseLines = { "/sdk/a/    @alice", "/sdk/b/    @bob" };
            string[] compareLines = { "/sdk/a/    @alice" };

            List<EntryDifference> differences = Compare(baseLines, compareLines);

            Assert.That(differences, Has.Count.EqualTo(1));
            Assert.That(differences[0].Kind, Is.EqualTo(DifferenceKind.MissingFromCompare));
            Assert.That(differences[0].Index, Is.EqualTo(1));
        }

        [Test]
        public void EntryMissingFromBaseIsReported()
        {
            string[] baseLines = { "/sdk/a/    @alice" };
            string[] compareLines = { "/sdk/a/    @alice", "/sdk/b/    @bob" };

            List<EntryDifference> differences = Compare(baseLines, compareLines);

            Assert.That(differences, Has.Count.EqualTo(1));
            Assert.That(differences[0].Kind, Is.EqualTo(DifferenceKind.MissingFromBase));
            Assert.That(differences[0].Index, Is.EqualTo(1));
        }

        [Test]
        public void MultipleFieldChangesOnOneEntryAreAllReported()
        {
            string[] baseLines = { "# PRLabel: %Tables", "/sdk/tables/    @alice" };
            string[] compareLines = { "# PRLabel: %Storage", "/sdk/tables/    @bob" };

            List<EntryDifference> differences = Compare(baseLines, compareLines);

            Assert.That(differences.Select(d => d.Field), Is.EquivalentTo(new[] { "SourceOwners", "PRLabels" }));
            Assert.That(differences.All(d => d.Index == 0), Is.True);
        }

        [Test]
        public void DifferenceCarriesLineNumbersForBothFiles()
        {
            string[] baseLines = { "/sdk/tables/    @alice" };
            string[] compareLines = { "", "", "/sdk/tables/    @bob" };

            EntryDifference difference = Compare(baseLines, compareLines).Single();

            Assert.That(difference.BaseLine, Is.EqualTo(0));
            Assert.That(difference.CompareLine, Is.EqualTo(2));
        }

        #endregion
    }
}
