# -------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
# --------------------------------------------------------------------------

"""
Module for handling chat thread resolution requests in APIView Copilot.
"""

import json

from src._database_manager import DatabaseManager
from src._memory_utils import check_for_duplicate_memory, merge_and_save_memory
from src._prompt_runner import run_prompt


def handle_thread_resolution_request(
    *, comments: list[dict], language: str, package_name: str, code: str, source_comment_id: str = None
) -> str:
    """
    Handles the chat thread resolution request by parsing the comments and executing the plan.
    """
    if not comments:
        return "No comments provided."

    action_results = _parse_action(language=language, code=code, package_name=package_name, comments=comments)
    action = action_results.get("action")
    if action == "record_result":
        plan = _parse_plan(
            language=language,
            code=code,
            package_name=package_name,
            comments=comments,
            reasoning=action_results.get("reasoning", ""),
        )
        results = _execute_plan(
            plan=plan,
            is_exception=False,
            package_name=package_name,
            source_comment_id=source_comment_id,
        )
        return _summarize_results(results)
    elif action == "record_exception":
        plan = _parse_plan(
            language=language,
            code=code,
            package_name=package_name,
            comments=comments,
            reasoning=action_results.get("reasoning", ""),
        )
        results = _execute_plan(
            plan=plan,
            is_exception=True,
            package_name=package_name,
            source_comment_id=source_comment_id,
        )
        return _summarize_results(results)
    elif action == "no_action":
        return f"No action required: {action_results.get('reasoning')}"
    elif action == "unclear":
        return f"Indeterminate: {action_results.get('reasoning')}"
    else:
        return "Something went wrong!"


def _parse_action(*, language: str, code: str, package_name: str, comments: list[dict]):
    inputs = {
        "language": language,
        "code": code,
        "package_name": package_name,
        "comments": comments,
    }
    raw_results = run_prompt(folder="thread_resolution", filename="parse_thread_resolution_action", inputs=inputs)
    try:
        results = json.loads(raw_results)
        return results
    except json.JSONDecodeError:
        return raw_results


def _parse_plan(*, language: str, code: str, package_name: str, comments: list[dict], reasoning: str):
    inputs = {
        "language": language,
        "code": code,
        "package_name": package_name,
        "comments": comments,
        "reasoning": reasoning,
    }
    raw_results = run_prompt(folder="thread_resolution", filename="parse_thread_resolution_to_memory", inputs=inputs)
    try:
        results = json.loads(raw_results)
        return results
    except json.JSONDecodeError:
        return raw_results


def _execute_plan(*, plan: dict, is_exception: bool, package_name: str, source_comment_id: str = None):
    """
    Executes the plan generated by the agent.
    """
    db_manager = DatabaseManager.get_instance()
    guideline_ids = plan.get("guideline_ids", [])
    raw_memory = plan.get("memory", {})
    raw_memory["source"] = "thread_resolution"
    if source_comment_id:
        raw_memory["source_comment_id"] = source_comment_id
    raw_memory["is_exception"] = is_exception

    # TODO: revise as we implement service silos
    raw_memory["service"] = package_name if is_exception else None

    raw_examples = raw_memory.pop("related_examples", [])

    # TODO: Remove service silo logic once we implement service silos
    example_service = package_name if is_exception else None

    # Check for duplicate memories before creating
    merge_result = check_for_duplicate_memory(
        raw_memory=raw_memory, guideline_ids=guideline_ids
    )
    if merge_result is not None:
        return merge_and_save_memory(
            merge_result=merge_result,
            raw_memory=raw_memory,
            guideline_ids=guideline_ids,
            raw_examples=raw_examples,
            example_service=example_service,
        )

    return db_manager.save_memory_with_links(
        raw_memory=raw_memory,
        guideline_ids=guideline_ids,
        raw_examples=raw_examples,
        example_service=example_service,
    )


def _summarize_results(results: dict):
    """
    Summarizes the results of the plan execution.
    """
    inputs = {
        "results": results,
    }
    try:
        summary = run_prompt(folder="thread_resolution", filename="summarize_actions", inputs=inputs)
        return summary
    except Exception as e:
        print(f"Error summarizing results: {e}")
        return "Error summarizing results."
