# Uncomment the next line to define a global platform for your project
platform :macos, '11.3'

target 'SwiftAPIView' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  use_modular_headers!

  # Pods for SwiftAPIView
end
