tenants:
  - tenant: general_qa_bot
    channel_name: General
    channel_link: https://teams.cloud.microsoft/l/channel/19%3Af6d52ac6465c40ea80dc86b8be3825aa%40thread.skype/Azure%20SDK?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&allowXTenantAccess=False

  - tenant: azure_sdk_onboarding
    channel_name: Azure SDK Onboarding and E2E SDK
    channel_link: https://teams.cloud.microsoft/l/channel/19%3Ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%20SDK%20Onboarding%20and%20E2E%20SDK?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&allowXTenantAccess=False

  - tenant: typespec_channel_qa_bot
    channel_name: TypeSpec Discussion
    channel_link: https://teams.cloud.microsoft/l/channel/19%3A906c1efbbec54dc8949ac736633e6bdf%40thread.skype/TypeSpec%20Discussion?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&allowXTenantAccess=False