import { createFeedbackCard } from './feedback.js';
import { supportChannelCard } from './support-channel.js';

export function createContactCard() {
  const feedbackCard = createFeedbackCard();
  const feedbackAction = {
    type: 'Action.ShowCard',
    title: '👍Feedback👎',
    card: feedbackCard,
  };
  const supportChannelAction = {
    type: 'Action.ShowCard',
    title: '🕵️‍♂️Support Channels🕵️‍♀️',
    card: supportChannelCard,
  };
  const actions = [feedbackAction, supportChannelAction];
  const card = {
    type: 'AdaptiveCard',
    // adaptive card does not support FULL markdown in attachment, use message instead
    body: [
      {
        type: 'TextBlock',
        text: '🤖The responses are generated by AI and may contain outdated information. Please verify any important details independently. 🔁For follow-up questions, @mentioning the bot is recommended. 📝Please note that the bot is unable to reply to edited messages.',
        wrap: true,
      },
    ],
    actions,
    $schema: 'http://adaptivecards.io/schemas/adaptive-card.json',
    version: '1.6',
  };
  return card;
}
