import { createFeedbackCard } from './feedback.js';
import { supportChannelCard } from './support-channel.js';

export function createContactCard(conversationId: string, activity: string) {
  const feedbackCard = createFeedbackCard(conversationId, activity);
  const feedbackAction = {
    type: 'Action.ShowCard',
    title: '👍Feedback👎',
    card: feedbackCard,
  };
  const supportChannelAction = {
    type: 'Action.ShowCard',
    title: '🕵️‍♂️Support Channels🕵️‍♀️',
    card: supportChannelCard,
  };
  const actions = [feedbackAction, supportChannelAction];
  const card = {
    type: 'AdaptiveCard',
    // adaptive card does not support FULL markdown in attachment, use message instead
    body: [
      {
        type: 'TextBlock',
        text: '🤖The responses are generated by an AI model. Info may be outdated or incorrect - Please verify if important.',
        wrap: true,
      },
    ],
    actions,
    $schema: 'http://adaptivecards.io/schemas/adaptive-card.json',
    version: '1.6',
  };
  return card;
}
