import { createFeedbackCard } from './feedback.js';
import { supportChannelCard } from './support-channel.js';

export function createContactCard() {
  const feedbackCard = createFeedbackCard();
  const feedbackAction = {
    type: 'Action.ShowCard',
    title: '👍Feedback👎',
    card: feedbackCard,
  };
  const supportChannelAction = {
    type: 'Action.ShowCard',
    title: '🕵️‍♂️Support Channels🕵️‍♀️',
    card: supportChannelCard,
  };
  const actions = [feedbackAction, supportChannelAction];
  const card = {
    type: 'AdaptiveCard',
    // adaptive card does not support FULL markdown in attachment, use message instead
    body: [
      {
        type: 'TextBlock',
        text: '🤖 This response is generated by AI. Please review it before taking action.',
        wrap: true,
      },
      {
        type: 'TextBlock',
        text: '📝 The bot only responds to the original message. If a message is edited, it will not reply again.',
        wrap: true,
      },
    ],
    actions,
    $schema: 'http://adaptivecards.io/schemas/adaptive-card.json',
    // Currently Microsoft Teams doesn't fully support version 1.6, use 1.5 to ensure compatibility
    version: '1.5',
  };
  return card;
}
