import { test } from "node:test";
import assert from "node:assert/strict";
import { collectJava } from "../collect-java.ts";
import { collectPython } from "../collect-python.ts";
import { generatorHeader, parseMetadata, object } from "../metadata.ts";
import { acceptSnapshot } from "../dashboard/data.ts";
import { type SourceProvider, type ObservationContext } from "../collect-source.ts";

const date = "2026-10-09T12:34:56.1234567Z";
function provider(files: Record<string, string>): SourceProvider {
  return { paths: Object.keys(files), async readText(path) {
    if (!(path in files)) throw new Error(`Missing test source ${path}`);
    return files[path];
  } };
}
const context = (language: "java" | "python"): ObservationContext => ({
  repository: { name: language === "java" ? "Azure/azure-sdk-for-java" : "Azure/azure-sdk-for-python",
    commit: "a".repeat(40), isDirty: false }, collectedAt: date,
});
const generated = "// Code generated by Microsoft (R) AutoRest Code Generator.\nclass Example {}\n";
const pythonGenerated = "# Code generated by Microsoft (R) Python Code Generator.\nvalue = 1\n";

test("whole-file generator provenance uses leading comments, never Java symbols or member annotations", () => {
  assert.equal(generatorHeader(generated, "java"), true);
  assert.equal(generatorHeader("/* Copyright\n * Code generated by Microsoft (R) TypeSpec Code Generator.\n */\nclass X{}", "java"), true);
  for (const text of [
    "package p; import com.azure.core.annotation.Generated;\nclass X { @Generated String field; }",
    "/** Generator marker annotation. */\npublic @interface Generated {}",
    'class X { String text = "Code generated by Microsoft (R) AutoRest Code Generator."; }',
    "// Microsoft copyright. implementation model.\nclass GeneratedModelImpl {}",
  ]) assert.equal(generatorHeader(text, "java"), false);
  assert.equal(generatorHeader(pythonGenerated, "python"), true);
  assert.equal(generatorHeader('message = "Code generated by Microsoft (R) Python Code Generator."', "python"), false);
});
test("Java follows CI coordinates and copied/shared Scala origins with artifact-local exclusions", async () => {
  const root = "sdk/cosmos/azure-connector";
  const files = {
    "sdk/cosmos/ci.yml": "extends:\n  parameters:\n    Artifacts:\n      - name: azure-connector\n        groupId: com.azure.cosmos.spark\n",
    [`${root}/pom.xml`]: `<project><groupId>com.azure.cosmos.spark</groupId><artifactId>azure-connector</artifactId>
      <build><plugins>
        <plugin><artifactId>maven-resources-plugin</artifactId><executions><execution><id>copy</id>
          <goals><goal>copy-resources</goal></goals><configuration>
          <outputDirectory>\${project.build.directory}/shared-sources</outputDirectory><resources><resource>
          <directory>\${basedir}/../shared/src/main/scala</directory><excludes><exclude>**/ItemsBatchWriter.scala</exclude></excludes>
          </resource></resources></configuration></execution></executions></plugin>
        <plugin><artifactId>build-helper-maven-plugin</artifactId><executions><execution><id>sources</id>
          <goals><goal>add-source</goal></goals><configuration><sources>
          <source>\${project.build.directory}/shared-sources</source><source>\${basedir}/src/main/scala</source>
          </sources></configuration></execution></executions></plugin>
      </plugins></build></project>`,
    [`${root}/src/main/scala/ItemsBatchWriter.scala`]: "own replacement\n",
    "sdk/cosmos/shared/src/main/scala/ItemsBatchWriter.scala": "excluded origin\n",
    "sdk/cosmos/shared/src/main/scala/Helper.scala": "shared\n",
    [`${root}/src/test/scala/Test.scala`]: "not production\n",
    [`${root}/src/main/java/Generated.java`]: generated,
  };
  const result = acceptSnapshot(await collectJava(provider(files), context("java")));
  assert.equal(result.libraries.length, 1);
  assert.equal(result.summary.totalFiles, 3);
  assert.equal(result.summary.generatedLines, 2);
  assert.ok(result.libraries[0].files?.some((file) => file.path === `${root}/src/main/scala/ItemsBatchWriter.scala`));
  assert.equal(result.libraries[0].files?.some((file) => file.path === "sdk/cosmos/shared/src/main/scala/ItemsBatchWriter.scala"), false);
  assert.equal(result.libraries[0].files?.some((file) => file.path.includes("/test/")), false);
});
test("Java supports inherited source declarations, genuine empty starter jars and category exceptions", async () => {
  const files: Record<string, string> = {
    "sdk/parents/base/pom.xml": "<project><groupId>com.azure</groupId><artifactId>parent</artifactId><packaging>pom</packaging></project>",
    "sdk/demo/ci.yml": `extends:\n  parameters:\n    Artifacts:\n      - name: azure-core-management\n        groupId: com.azure\n      - name: spring-cloud-azure-resourcemanager\n        groupId: com.azure.spring\n      - name: azure-loadtesting\n        groupId: com.azure\n      - name: azure-core-test\n        groupId: com.azure\n`,
  };
  for (const [name, group] of [
    ["azure-core-management", "com.azure"], ["spring-cloud-azure-resourcemanager", "com.azure.spring"],
    ["azure-loadtesting", "com.azure"], ["azure-core-test", "com.azure"],
  ]) {
    files[`sdk/demo/${name}/pom.xml`] = `<project><parent><groupId>com.azure</groupId><artifactId>parent</artifactId><relativePath>../../parents/base/pom.xml</relativePath></parent><groupId>${group}</groupId><artifactId>${name}</artifactId></project>`;
  }
  files["sdk/demo/azure-loadtesting/src/main/java/Client.java"] = "class Client {}\n";
  const result = await collectJava(provider(files), context("java"));
  assert.equal(result.libraries.length, 3);
  assert.equal(result.libraries.find((library) => library.library === "com.azure:azure-core-management")?.category, "management");
  assert.equal(result.libraries.find((library) => library.library.startsWith("com.azure.spring:"))?.category, "data-plane");
  assert.equal(result.libraries.find((library) => library.library.startsWith("com.azure.spring:"))?.metrics.customRatio, null);
  assert.equal(result.excludedLibraries.find((library) => library.projectPath.includes("azure-core-test"))?.reason, "non-production-package");
});
test("Java rejects release/POM mismatches and unresolved source configuration instead of omitting source", async () => {
  const ci = "extends:\n  parameters:\n    Artifacts:\n      - name: azure-demo\n        groupId: com.azure\n";
  await assert.rejects(collectJava(provider({ "sdk/demo/ci.yml": ci }), context("java")), /matching POMs/);
  await assert.rejects(collectJava(provider({
    "sdk/demo/ci.yml": ci,
    "sdk/demo/azure-demo/pom.xml": "<project><groupId>com.azure</groupId><artifactId>azure-demo</artifactId><build><sourceDirectory>${unknown}/source</sourceDirectory></build></project>",
  }), context("java")), /unresolved Maven source property/);
});
test("Python honors namespace metadata, stubs, patch precedence, generator ownership and local vendor payload", async () => {
  const root = "sdk/demo/azure-example";
  const files = {
    [`${root}/pyproject.toml`]: '[project]\nname="azure-example"\n[tool.setuptools.packages.find]\ninclude=["azure_example*"]\nexclude=["azure_example.tests*"]\n',
    [`${root}/azure_example/__init__.py`]: "",
    [`${root}/azure_example/client.py`]: "# handwritten\nx = 1\n",
    [`${root}/azure_example/_generated/client.py`]: pythonGenerated,
    [`${root}/azure_example/_generated/_patch.py`]: pythonGenerated + "handwritten = 2\n",
    [`${root}/azure_example/_generated/_patch.pyi`]: "def patched() -> None: ...\n",
    [`${root}/azure_example/_generated/_serialization.py`]: "class Serializer: pass\n",
    [`${root}/azure_example/other/_model_base.py`]: "class HandwrittenModel: pass\n",
    [`${root}/azure_example/_vendor/storage/blob/client.py`]: "class Vendor: pass\n",
    [`${root}/azure_example/tests/test_client.py`]: "not production\n",
    [`${root}/azure_example/native.c`]: "not Python\n",
  };
  const result = acceptSnapshot(await collectPython(provider(files), context("python")));
  const evidence = result.libraries[0].files!;
  assert.equal(evidence.length, 8);
  assert.equal(evidence.find((file) => file.path.endsWith("_patch.py"))?.provenance, "custom");
  assert.equal(evidence.find((file) => file.path.endsWith("_patch.pyi"))?.provenance, "custom");
  assert.equal(evidence.find((file) => file.path.endsWith("_serialization.py"))?.evidence, "generator-output");
  assert.equal(evidence.find((file) => file.path.endsWith("_model_base.py"))?.provenance, "custom");
  assert.ok(evidence.some((file) => file.path.includes("/_vendor/")));
});
test("Python tooling-only TOML falls back to static setup literals and package-data discovery", async () => {
  const root = "sdk/demo/azure-example";
  const files = {
    [`${root}/pyproject.toml`]: "[tool.azure-sdk-build]\nmypy=false\n",
    [`${root}/setup.py`]: 'from setuptools import setup, find_packages\nNAME="azure-example"\nsetup(name=NAME,packages=find_packages(include=["azure.example*"]),package_data={"azure.example":["data/**/*.py"]})',
    [`${root}/azure/__init__.py`]: "",
    [`${root}/azure/example/__init__.py`]: "",
    [`${root}/azure/example/client.py`]: "code\n",
    [`${root}/azure/example/data/nested/payload.py`]: "runtime package data\n",
    [`${root}/tests/test_client.py`]: "not shipped\n",
  };
  const result = await collectPython(provider(files), context("python"));
  assert.equal(result.libraries[0].projectPath, `${root}/setup.py`);
  assert.equal(result.libraries[0].metrics.totalFiles, 3);
  assert.ok(result.libraries[0].files.some((file) => file.path.endsWith("data/nested/payload.py")));
});
test("Python excludes structurally proven noninstallable SDIST placeholders, not ordinary mention of sdist", () => {
  const values = parseMetadata([
    { path: "placeholder.py", kind: "setup", text: 'import sys\nfrom setuptools import setup\nif "sdist" in sys.argv:\n setup(name="azure-storage")\nelse:\n raise RuntimeError("deprecated")' },
    { path: "runtime.py", kind: "setup", text: 'from setuptools import setup\n# Supports sdist and wheels.\nsetup(name="azure-demo",packages=["azure_demo"])' },
    { path: "conditional.py", kind: "setup", text: 'from setuptools import setup\nif "sdist" in choices:\n setup(name="azure-demo")\nelse:\n raise RuntimeError("other mode")' },
  ]);
  assert.equal(object(values.get("placeholder.py"), "placeholder").sdist_only, true);
  assert.equal(object(values.get("runtime.py"), "runtime").sdist_only, false);
  assert.equal(object(values.get("conditional.py"), "conditional").sdist_only, false);
});
test("static setup metadata never executes package code and unsupported membership is explicit", async () => {
  const root = "sdk/demo/azure-demo";
  await assert.rejects(collectPython(provider({
    [`${root}/setup.py`]: 'from setuptools import setup\nsetup(name="azure-demo",packages=__import__("os").listdir("."))',
  }), context("python")), /Unsupported static setup expression/);
  assert.throws(() => parseMetadata([{ path: "bad.xml", kind: "xml", text: "<!DOCTYPE root [<!ENTITY x 'bad'>]><root>&x;</root>" }]),
    /DTD\/entity declarations/);
});
