import { OperationParameter, OperationURLParameter, OperationQueryParameter } from "@azure/core-client";
export declare const accept: OperationParameter;
export declare const $host: OperationURLParameter;
export declare const apiVersion: OperationQueryParameter;
export declare const nextLink: OperationURLParameter;
export declare const subscriptionId: OperationURLParameter;
export declare const resourceGroupName: OperationURLParameter;
export declare const dataProductName: OperationURLParameter;
export declare const contentType: OperationParameter;
export declare const resource: OperationParameter;
export declare const properties: OperationParameter;
export declare const body: OperationParameter;
export declare const body1: OperationParameter;
export declare const body2: OperationParameter;
export declare const body3: OperationParameter;
export declare const body4: OperationParameter;
export declare const dataTypeName: OperationURLParameter;
export declare const resource1: OperationParameter;
export declare const properties1: OperationParameter;
export declare const body5: OperationParameter;
//# sourceMappingURL=parameters.d.ts.map