/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CandidateDecision = {
  [k: string]: unknown;
} & {
  candidateId: string;
  decision: "approve" | "reject";
  severity?: "high" | "medium" | "low";
  rationale: string;
};
export type CandidateDecisions = CandidateDecision[];
export type InferenceResult = {
  [k: string]: unknown;
} & {
  requestId: string;
  decision: "candidates" | "no-impact" | "blocked";
  rationale: string;
  candidates: InferredCandidate[];
};
export type InferredCandidate = {
  [k: string]: unknown;
} & {
  id: string;
  dimension: "rest" | "downstream";
  rule: string;
  defaultSeverity: "high" | "medium" | "low";
  actual: string;
  expected: string;
  crossLanguageDefinitionId?: string;
  operationIds: string[];
  evidenceFactIds: string[];
};
export type CatalogId = string;
export type FetchedDocument = {
  [k: string]: unknown;
} & {
  catalogId: CatalogId;
  retrievedAt: string;
  contentHash: string;
  bytes: number;
  guidance: Guidance[];
  noRelevantGuidance: boolean;
} & {
  catalogId: CatalogId;
  retrievedAt: string;
  contentHash: string;
  bytes: number;
  guidance: Guidance[];
  noRelevantGuidance: boolean;
} & {
  catalogId: CatalogId;
  retrievedAt: string;
  contentHash: string;
  bytes: number;
  guidance: Guidance[];
  noRelevantGuidance: boolean;
} & {
  catalogId: CatalogId;
  retrievedAt: string;
  contentHash: string;
  bytes: number;
  guidance: Guidance[];
  noRelevantGuidance: boolean;
};
export type ComplianceJudgment = {
  [k: string]: unknown;
} & {
  reviewUnitId: string;
  applicableGuidance: ApplicableGuidance[];
  declarationNames?: string[];
  /**
   * @deprecated
   * Legacy alternative to declarationNames; IDs must still be valid for the owning intent.
   */
  declarationIds?: string[];
  decision: "applicable-pass" | "applicable-fail" | "no-applicable-guidance" | "not-assessed";
  title?: string;
  severity?: "high" | "medium" | "low";
  expected?: string;
  actual: string;
  rationale: string;
};
export type SdkNamingFinding = {
  [k: string]: unknown;
} & {
  reviewUnitId?: string;
  declaration: string;
  currentSdkName: string;
  recommendedSdkName?: string;
  languageScope: string;
  decision: "recommend" | "blocked";
  rule: string;
  rationale: string;
  compatibilityEvidence: string;
  verification: "proposed" | "supplied-generated" | "applied";
  sourceLocation?: string;
};

export interface TypeSpecAssessmentCompactAgentDecisions {
  schemaVersion: 1;
  semanticSummaries: SemanticSummary[];
  restDecisions: CandidateDecisions;
  downstreamDecisions: CandidateDecisions;
  inferenceResults?: InferenceResult[];
  catalogScores: CatalogScore[];
  /**
   * @maxItems 4
   */
  fetchedDocuments:
    | []
    | [FetchedDocument]
    | [FetchedDocument, FetchedDocument]
    | [FetchedDocument, FetchedDocument, FetchedDocument]
    | [FetchedDocument, FetchedDocument, FetchedDocument, FetchedDocument];
  failedRetrievals: FailedRetrieval[];
  searchBlockers: string[];
  complianceJudgments: ComplianceJudgment[];
  sdkNamingReview?: SdkNamingReview;
  overallConfidence: "high" | "medium" | "low";
  blockers: string[];
}
export interface SemanticSummary {
  reviewUnitId: string;
  title: string;
  summary: string;
}
export interface CatalogScore {
  catalogId: CatalogId;
  exactSymbol: 0 | 4;
  patternCategory: 0 | 3;
  servicePlane: 0 | 2;
  changeContext: 0 | 1;
  rationale: string;
}
export interface Guidance {
  section: string;
  excerpt: string;
  queryTerms: string[];
  /**
   * @maxItems 2
   */
  examples: [] | [string] | [string, string];
  /**
   * @deprecated
   * Legacy field ignored by the materializer; applicability is derived from citing judgments.
   */
  applicableDeclarationIds?: string[];
}
export interface FailedRetrieval {
  catalogId: CatalogId;
  error: string;
}
export interface ApplicableGuidance {
  catalogId: CatalogId;
  guidanceSection: string;
}
export interface SdkNamingReview {
  summary: string;
  coverage: SdkNamingCoverage[];
  findings: SdkNamingFinding[];
  blockers: string[];
}
export interface SdkNamingCoverage {
  language: string;
  serviceType: "arm" | "data-plane" | "unknown";
  profile?: string;
  status: "reviewed" | "not-covered" | "not-assessed";
  rationale: string;
}
