/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Decisions = {
  [k: string]: unknown;
}[];
export type SdkNamingFinding = {
  [k: string]: unknown;
} & {
  id: string;
  reviewUnitId?: string;
  declaration: string;
  currentSdkName: string;
  recommendedSdkName?: string;
  languageScope: string;
  decision: "recommend" | "blocked";
  rule: string;
  rationale: string;
  compatibilityEvidence: string;
  verification: "proposed" | "supplied-generated" | "applied";
  sourceLocation?: string;
};

export interface TypeSpecAssessmentJudgment {
  schemaVersion: 1;
  semanticIntents: {
    reviewUnitId: string;
    title: string;
    summary: string;
  }[];
  restDecisions: Decisions;
  downstreamDecisions: Decisions;
  complianceDecisions: {
    [k: string]: unknown;
  }[];
  sdkNaming?: SdkNamingDimension;
  overallConfidence: "high" | "medium" | "low";
  blockers: string[];
}
export interface SdkNamingDimension {
  status: "passed" | "failed" | "not-assessed";
  summary: string;
  coverage: SdkNamingCoverage[];
  findings: SdkNamingFinding[];
  blockers: string[];
}
export interface SdkNamingCoverage {
  language: string;
  serviceType: "arm" | "data-plane" | "unknown";
  profile?: string;
  status: "reviewed" | "not-covered" | "not-assessed";
  rationale: string;
}
