"use strict";
/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
const arm_networkanalytics_1 = require("@azure/arm-networkanalytics");
const identity_1 = require("@azure/identity");
const dotenv = tslib_1.__importStar(require("dotenv"));
dotenv.config();
/**
 * This sample demonstrates how to Delete data for data type.
 *
 * @summary Delete data for data type.
 * x-ms-original-file: specification/networkanalytics/resource-manager/Microsoft.NetworkAnalytics/stable/2023-11-15/examples/DataTypes_DeleteData_MaximumSet_Gen.json
 */
async function dataTypesDeleteDataMaximumSetGen() {
    const subscriptionId = process.env["NETWORKANALYTICS_SUBSCRIPTION_ID"] ||
        "00000000-0000-0000-0000-00000000000";
    const resourceGroupName = process.env["NETWORKANALYTICS_RESOURCE_GROUP"] || "aoiresourceGroupName";
    const dataProductName = "dataproduct01";
    const dataTypeName = "datatypename";
    const body = {};
    const credential = new identity_1.DefaultAzureCredential();
    const client = new arm_networkanalytics_1.MicrosoftNetworkAnalytics(credential, subscriptionId);
    const result = await client.dataTypes.beginDeleteDataAndWait(resourceGroupName, dataProductName, dataTypeName, body);
    console.log(result);
}
/**
 * This sample demonstrates how to Delete data for data type.
 *
 * @summary Delete data for data type.
 * x-ms-original-file: specification/networkanalytics/resource-manager/Microsoft.NetworkAnalytics/stable/2023-11-15/examples/DataTypes_DeleteData_MinimumSet_Gen.json
 */
async function dataTypesDeleteDataMinimumSetGen() {
    const subscriptionId = process.env["NETWORKANALYTICS_SUBSCRIPTION_ID"] ||
        "00000000-0000-0000-0000-00000000000";
    const resourceGroupName = process.env["NETWORKANALYTICS_RESOURCE_GROUP"] || "aoiresourceGroupName";
    const dataProductName = "dataproduct01";
    const dataTypeName = "datatypename";
    const body = {};
    const credential = new identity_1.DefaultAzureCredential();
    const client = new arm_networkanalytics_1.MicrosoftNetworkAnalytics(credential, subscriptionId);
    const result = await client.dataTypes.beginDeleteDataAndWait(resourceGroupName, dataProductName, dataTypeName, body);
    console.log(result);
}
async function main() {
    dataTypesDeleteDataMaximumSetGen();
    dataTypesDeleteDataMinimumSetGen();
}
main().catch(console.error);
//# sourceMappingURL=dataTypesDeleteDataSample.js.map