<#
.SYNOPSIS
Evaluates Copilot pipeline fixes for a set of Azure SDK repositories.

.PARAMETER Owner
GitHub repository owner.

.PARAMETER RepositoriesJson
JSON array containing the repository names to evaluate.

.PARAMETER SinceDays
Number of one-day evaluation reports to generate, ending at the current UTC time and then each
preceding day.

.PARAMETER JobTimeoutMinutes
Overall pipeline job timeout used to calculate a per-repository timeout.

.PARAMETER EvalArtifactDir
Directory where evaluation reports are written.

.PARAMETER DashboardHistoryDir
Directory containing previously published evaluation reports. Historical reports are merged with
reports generated by this run when creating dashboard.json.

.PARAMETER MetricsPrefix
Blob key prefix included in the report directory layout.

.PARAMETER AzSdkPath
Path to the azsdk CLI executable.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $Owner,

    [string] $RepositoriesJson = $env:REPOSITORIES_JSON,

    [Parameter(Mandatory = $true)]
    [int] $SinceDays,

    [Parameter(Mandatory = $true)]
    [int] $JobTimeoutMinutes,

    [Parameter(Mandatory = $true)]
    [string] $EvalArtifactDir,

    [Parameter(Mandatory = $true)]
    [string] $DashboardHistoryDir,

    [Parameter(Mandatory = $true)]
    [string] $MetricsPrefix,

    [Parameter(Mandatory = $true)]
    [string] $AzSdkPath
)

Set-StrictMode -Version 4
$ErrorActionPreference = 'Stop'

$githubToken = $env:GITHUB_TOKEN
if ([string]::IsNullOrWhiteSpace($githubToken)) {
    throw "GITHUB_TOKEN is not set. Ensure the 'Login to GitHub' pipeline step completed and exported GH_TOKEN."
}

$env:GITHUB_TOKEN = $githubToken.Trim()
try {
    Invoke-RestMethod `
        -Uri 'https://api.github.com/installation/repositories?per_page=1' `
        -Headers @{
            Authorization = "Bearer $env:GITHUB_TOKEN"
            Accept = 'application/vnd.github+json'
            'User-Agent' = 'azure-sdk-pipeline-fix-evaluator'
            'X-GitHub-Api-Version' = '2022-11-28'
        } `
        -Method Get | Out-Null
}
catch {
    throw "GITHUB_TOKEN was rejected by GitHub. Check the Azure SDK Automation App installation and repository permissions, then rerun the pipeline. $($_.Exception.Message)"
}

$runUntil = (Get-Date).ToUniversalTime()
$repositories = @($RepositoriesJson | ConvertFrom-Json)

if ($repositories.Count -eq 0) {
    throw 'At least one repository must be provided.'
}
if ($SinceDays -le 0) {
    throw 'SinceDays must be greater than zero.'
}

$shareableMinutes = $JobTimeoutMinutes * 0.75
$evaluationCount = $repositories.Count * $SinceDays
$perEvaluationMinutes = [int][math]::Max(1, [math]::Floor($shareableMinutes / $evaluationCount))
$timeoutMilliseconds = [int][TimeSpan]::FromMinutes($perEvaluationMinutes).TotalMilliseconds
Write-Host "Job timeout ${JobTimeoutMinutes}m over $evaluationCount evaluation(s): allowing ${perEvaluationMinutes}m each."

$failed = @()

foreach ($repository in $repositories) {
    Write-Host "##[group]Evaluating $Owner/$repository"

    $repositoryDirectory = Join-Path $EvalArtifactDir "$MetricsPrefix/$repository"
    New-Item -ItemType Directory -Force -Path $repositoryDirectory | Out-Null

    for ($dayOffset = 0; $dayOffset -lt $SinceDays; $dayOffset++) {
        $evaluationUntil = $runUntil.AddDays(-$dayOffset)
        $reportDate = $evaluationUntil.ToString('yyyy-MM-dd')
        $reportPath = Join-Path $repositoryDirectory "$reportDate.json"
        $standardErrorPath = Join-Path $repositoryDirectory "$reportDate.stderr.log"
        Remove-Item -Path $reportPath, $standardErrorPath -Force -ErrorAction SilentlyContinue

        $evaluationArguments = @(
            'eng', 'evaluate', $Owner, $repository,
            '--since-days', 1,
            '--until', $evaluationUntil.ToString('o'),
            '--output', 'json'
        )

        $process = Start-Process `
            -FilePath $AzSdkPath `
            -ArgumentList $evaluationArguments `
            -RedirectStandardOutput $reportPath `
            -RedirectStandardError $standardErrorPath `
            -PassThru
        $completed = $process.WaitForExit($timeoutMilliseconds)

        if (-not $completed) {
            $process.Kill($true)
            $process.WaitForExit()
        }

        if (Test-Path $standardErrorPath) {
            $standardError = Get-Content -Raw -Path $standardErrorPath
        } else {
            $standardError = ''
        }
        Remove-Item -Path $standardErrorPath -Force -ErrorAction SilentlyContinue

        $evaluationName = "$repository/$reportDate"
        if (-not $completed) {
            Write-Host "##vso[task.logissue type=error]eng evaluate for $evaluationName exceeded ${perEvaluationMinutes}m and was terminated"
            if (-not [string]::IsNullOrWhiteSpace($standardError)) {
                Write-Host $standardError
            }
            Remove-Item -Path $reportPath -Force -ErrorAction SilentlyContinue
            $failed += $evaluationName
            continue
        }

        $exitCode = $process.ExitCode
        if ($exitCode -ne 0) {
            Write-Host "##vso[task.logissue type=error]eng evaluate failed for $evaluationName with exit code $exitCode"
            if (-not [string]::IsNullOrWhiteSpace($standardError)) {
                Write-Host $standardError
            }
            Remove-Item -Path $reportPath -Force -ErrorAction SilentlyContinue
            $failed += $evaluationName
            continue
        }

        try {
            $report = Get-Content -Raw -Path $reportPath | ConvertFrom-Json
        } catch {
            Write-Host "##vso[task.logissue type=error]eng evaluate produced invalid JSON for ${evaluationName}: $_"
            Remove-Item -Path $reportPath -Force -ErrorAction SilentlyContinue
            $failed += $evaluationName
            continue
        }

        $hasResults = $report.PSObject.Properties.Name -contains 'results' -and $null -ne $report.results
        $count = if ($hasResults) { @($report.results).Count } else { 0 }
        Write-Host "$evaluationName -> $reportPath ($count evaluation(s))"
    }
    Write-Host '##[endgroup]'
}

if ($failed.Count -eq $evaluationCount) {
    throw 'Evaluation failed for every repository; nothing to publish.'
}

$reportsByKey = @{}
$reportRoots = @($DashboardHistoryDir, $EvalArtifactDir) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
$escapedPrefix = [regex]::Escape($MetricsPrefix.Trim('/'))
$reportPathPattern = "^$escapedPrefix/[^/]+/\d{4}-\d{2}-\d{2}\.json$"

foreach ($reportRoot in $reportRoots) {
    if (-not (Test-Path -Path $reportRoot -PathType Container)) {
        continue
    }

    foreach ($reportFile in Get-ChildItem -Path $reportRoot -Filter '*.json' -Recurse -File) {
        $key = [IO.Path]::GetRelativePath($reportRoot, $reportFile.FullName).Replace('\', '/')
        if ($key -notmatch $reportPathPattern) {
            continue
        }

        try {
            $rawReport = Get-Content -Raw -Path $reportFile.FullName | ConvertFrom-Json
        } catch {
            throw "Cannot build dashboard snapshot because report '$key' contains invalid JSON: $_"
        }

        $reportsByKey[$key] = [ordered]@{
            key = $key
            report = $rawReport
        }
    }
}

if ($reportsByKey.Count -eq 0) {
    throw 'No valid evaluation reports were available for dashboard.json.'
}

$dashboard = [ordered]@{
    schemaVersion = 1
    generatedAt = [DateTime]::UtcNow.ToString('o')
    reports = @($reportsByKey.Values | Sort-Object { $_.key })
}
$dashboardPath = Join-Path $EvalArtifactDir "$MetricsPrefix/dashboard.json"
$dashboard | ConvertTo-Json -Depth 100 | Set-Content -Path $dashboardPath -Encoding utf8
Write-Host "Dashboard snapshot -> $dashboardPath ($($reportsByKey.Count) report(s))"

if ($failed.Count -gt 0) {
    Write-Host "##vso[task.complete result=SucceededWithIssues;]Evaluation failed for: $($failed -join ', ')"
}
