.create-or-alter function ManagedDefinition
{
    BuildDefinition
    | where Variables contains "meta"
    | extend metas = parse_json(Variables)
    | extend Platform = metas["meta.platform"].value
    | extend Feature = metas["meta.component"].value
    | extend Category = metas["meta.category"].value
    | project-away metas
    | summarize arg_max(BuildDefinitionRevision, *) by BuildDefinitionId, ProjectId
}