pr: none

trigger: none

pool:
  name: azsdk-pool
  demands: ImageOverride -equals ubuntu-24.04

parameters:
  - name: Reviews
    type: string
    default: '[{"ReviewID":"<reviewid>","RevisionID":"<revisionId>","FileID":"<fileid>","FileName":"<fileName>"}]'
  - name: APIViewURL
    type: string
    default: 'https://apiview.dev'
  - name: StorageContainerUrl
    type: string
    default: ''

variables:
  PythonVersion: '3.10'
  ApiStubVersion: '0.3.28'

jobs:
- job: CreatePythonReviewCodeFile
  displayName: 'Create Python API review token file'

  variables:
  - template: /eng/pipelines/templates/variables/globals.yml

  steps:
  - template: /eng/pipelines/templates/steps/use-python-version.yml
    parameters:
      versionSpec: '$(PythonVersion)'

  # globally sets PIP_INDEX_URL which `pip` will use by default going forward after this task completes
  - task: PipAuthenticate@1
    displayName: 'Pip Authenticate to feed'
    inputs:
      artifactFeeds: 'public/azure-sdk-for-python'
      onlyAddExtraIndex: false

  - script: |
      python -m pip install virtualenv aiohttp chardet trio
      python -m pip install apiview-stub-generator==$(ApiStubVersion)
    displayName: 'Install apiview-stub-generator'

  - template: /eng/pipelines/templates/steps/apiview-review-gen.yml
    parameters:
      Reviews: $(Reviews)
      APIViewURL: $(APIViewURL)
      StorageContainerUrl: $(StorageContainerUrl)
      ApiviewGenScript: './Create-Apiview-Token-Python.ps1'