pr: none
trigger: none

schedules:
  - cron: '0 0,4,8,12,16,20 * * *'
    displayName: AzureCloud
    branches:
      include:
        - main
    always: true
  - cron: '5 0,4,8,12,16,20 * * *'
    displayName: Playground
    branches:
      include:
        - main
    always: true
  - cron: '15 0,4,8,12,16,20 * * *'
    displayName: Cosmos
    branches:
      include:
        - main
    always: true
  - cron: '20 0,4,8,12,16,20 * * *'
    displayName: GithubCopilot
    branches:
      include:
        - main
    always: true
  - cron: '25 0,4,8,12,16,20 * * *'
    displayName: TME
    branches:
      include:
        - main
    always: true

parameters:
  - name: DryRun
    type: boolean
    default: false
  - name: GroupFilter
    type: string
    default: '*'
  - name: Pool
    type: string
    default: azsdk-pool
  - name: Subscriptions
    type: object
    default:
      - JobName: AzureCloud
        ScheduleName: AzureCloud
        DisplayName: AzureCloud - Resource Cleanup
        ServiceConnection: azure-sdk-tests
        AdditionalParameters: "-DeleteNonCompliantGroups -DeleteArmDeployments"
        # TODO: Enable strict resource cleanup after pre-existing static groups have been handled
        # AdditionalParameters: "-DeleteNonCompliantGroups"
      - JobName: Playground
        ScheduleName: Playground
        DisplayName: AzureCloud Playground - Resource Cleanup
        ServiceConnection: azure-sdk-tests-playground
        AdditionalParameters: "-DeleteNonCompliantGroups -DeleteArmDeployments -MaxLifespanDeleteAfterHours 240"
      - JobName: Cosmos
        ScheduleName: Cosmos
        DisplayName: AzureCloud Cosmos - Resource Cleanup
        ServiceConnection: azure-sdk-tests-cosmos
        SubscriptionConfigurations:
          - $(sub-config-cosmos-azure-cloud-test-resources)
      - JobName: GithubCopilot
        ScheduleName: GithubCopilot
        DisplayName: GithubCopilotForAzureTestingSubscription
        ServiceConnection: GithubCopilotForAzure-Testing
        AdditionalParameters: "-DeleteNonCompliantGroups -DeleteArmDeployments -CheckPrefix $false"
      - JobName: TME
        ScheduleName: TME
        DisplayName: AzureCloud TME - Resource Cleanup
        ServiceConnection: azure-sdk-tests-public
        AdditionalParameters: "-DeleteNonCompliantGroups -DeleteArmDeployments"
      # - DisplayName: AzureCloud Storage NET - Resource Cleanup
      #   SubscriptionConfigurations:
      #     - $(sub-config-storage-test-resources-net)

stages:
- stage: Run

  variables:
  - template: /eng/pipelines/templates/variables/globals.yml
  - name: DailyCacheKey
    value: $[format('{0:ddMMyyyy}', pipeline.startTime)]
  - name: CachePath
    value: CleanupCache

  jobs:
  - ${{ each subscription in parameters.Subscriptions }}:
    - job: ${{ subscription.JobName }}
      displayName: ${{ subscription.DisplayName }}
      condition: or(ne(variables['Build.Reason'], 'Schedule'), eq(variables['Build.CronSchedule.DisplayName'], '${{ subscription.ScheduleName }}'))
      timeoutInMinutes: 120  # sometimes RP throttling slows down the cleanup script
      pool:
        name: azsdk-pool
        demands: ImageOverride -equals ubuntu-24.04

      steps:
      - template: /eng/common/pipelines/templates/steps/cache-ps-modules.yml

      - task: Cache@2
        inputs:
          # CacheSalt is an optional variable that can be overridden at pipeline runtime to
          # force invalidate the cache.
          # DailyCacheKey will trigger a new cache entry to refresh once per day.
          key: '"$(CacheSalt)" | "$(DailyCacheKey)" | $(Build.SourcesDirectory)/eng/scripts/live-test-resource-cleanup.ps1'
          path: $(CachePath)
        displayName: Cache Github Alias Mappings

      # Register the dogfood environment to clean up any custom subscriptions in it
      - template: /eng/common/TestResources/setup-environments.yml

      - task: AzureCLI@2
        displayName: Authenticate to OpenSource API
        inputs:
          azureSubscription: opensource-api-connection
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            $jwt_accessToken = az account get-access-token --resource "api://2efaf292-00a0-426c-ba7d-f5d2b214b8fc" --query "accessToken" --output tsv
            Write-Host "##vso[task.setvariable variable=opensource-api-token;isSecret=true]$jwt_accessToken"

      - template: ./live-test-cleanup-template.yml
        parameters:
          DryRun: ${{ parameters.DryRun }}
          GroupFilter: ${{ parameters.GroupFilter }}
          DisplayName: ${{ subscription.DisplayName }}
          ServiceConnection: ${{ subscription.ServiceConnection }}
          SubscriptionConfigurationFilePaths: ${{ subscription.SubscriptionConfigurationFilePaths }}
          SubscriptionConfigurations: ${{ subscription.SubscriptionConfigurations }}
          GithubAliasCachePath: $(CachePath)/github-alias-mappings.txt
          AdditionalParameters: ${{ subscription.AdditionalParameters }}
          Pool: ${{ parameters.Pool }}
