# Configure notifications in Azure DevOps
trigger: none

pr: none

parameters:
  - name: CodeownerTargetRepos
    type: object
    default:
      - RepoName: azure-sdk-for-net
        DraftPr: true
      # - RepoName: azure-sdk-for-java
      #   DraftPr: true
      # - RepoName: azure-sdk-for-js
      #   DraftPr: true
      # - RepoName: azure-sdk-for-python
      #   DraftPr: true
      # - RepoName: azure-sdk-for-go
      #   DraftPr: true
      # - RepoName: azure-sdk-for-cpp
      #   DraftPr: true
      # - RepoName: azure-sdk-for-rust
      #   DraftPr: true


stages:
- stage: Run

  variables:
  - template: ./templates/variables/globals.yml

  jobs:
  - job: Run
    timeoutInMinutes: 120
    pool:
      name: azsdk-pool
      demands: ImageOverride -equals ubuntu-24.04

    variables:
      Organization: azure-sdk
      Project: internal
      DotNetDevOpsFeed: "https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json"
      OutputPath: '$(Agent.BuildDirectory)/pipelineOwners.json'
      RepoLabelUri: "https://azuresdkartifacts.blob.core.windows.net/azure-sdk-write-teams/repository-labels-blob"
      TeamUserUri: "https://azuresdkartifacts.blob.core.windows.net/azure-sdk-write-teams/azure-sdk-write-teams-blob"
      UserOrgUri: "https://azuresdkartifacts.blob.core.windows.net/azure-sdk-write-teams/user-org-visibility-blob"
      RepoListFile: "$(Build.SourcesDirectory)/tools/github/data/repositories.txt"

    steps:
      - template: /eng/pipelines/templates/steps/install-dotnet.yml

      - task: AzureCLI@2
        displayName: 'Fetch and store team/user data'
        inputs:
          azureSubscription: 'Azure SDK Artifacts'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            dotnet run -rUri "$(RepoLabelUri)" -tUri "$(TeamUserUri)" -uUri "$(UserOrgUri)" -rlFile "$(RepoListFile)"
          workingDirectory: tools/github-team-user-store/GitHubTeamUserStore/GitHubTeamUserStore
        env:
          GITHUB_TOKEN: $(azuresdk-github-pat)

      - task: DotNetCoreCLI@2
        displayName: 'Install Pipeline Owners Extractor'
        inputs:
          command: custom
          custom: 'tool'
          arguments: 'install --global --add-source "$(DotNetDevOpsFeed)" --version "$(PipelineOwnersExtractorVersion)" "Azure.Sdk.Tools.PipelineOwnersExtractor"'
          workingDirectory: '$(Agent.BuildDirectory)'
      - task: AzureCLI@2
        displayName: Run Pipeline Owners Extractor
        inputs:
          azureSubscription: 'opensource-api-connection'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: pipeline-owners-extractor --output "$(OutputPath)"
      - publish: $(OutputPath)
        displayName: Publish pipelineOwners artifact
        artifact: pipelineOwners
        condition: succeededOrFailed()

- stage: GenerateCodeowners
  variables:
    - template: /eng/pipelines/templates/variables/image.yml

  jobs:
    - job: UpdateCodeownersFiles
      pool:
        name: $(LINUXPOOL)
        demands: ImageOverride -equals $(LINUXVMIMAGE)

      variables:
        PRBranchName: "automation/codeowners-update"

      steps:
        # Check out current repo to get azure-sdk-mcp.ps1 and login-to-github.ps1
        # TODO: Sparse checkout eng/?
        - checkout: self

        - template: /eng/common/pipelines/templates/steps/install-azsdk-cli.yml

        - template: /eng/common/pipelines/templates/steps/login-to-github.yml

        - ${{ each repo in parameters.CodeownerTargetRepos }}:
          - template: /eng/common/pipelines/templates/steps/sparse-checkout.yml
            parameters:
              Repositories:
                - Paths:
                  - .github/CODEOWNERS
                - Name: "Azure/${{ repo.RepoName }}"
                  Commitish: main
                  WorkingDirectory: "$(Build.SourcesDirectory)/${{ repo.RepoName }}"

          - pwsh: git checkout -b "$(PRBranchName)"
            displayName: "Create $(PRBranchName) branch for ${{ repo.RepoName }}"

          - task: AzureCLI@2
            displayName: "Update CODEOWNERS for ${{ repo.RepoName }}"
            inputs:
              azureSubscription: 'opensource-api-connection'
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                & "$(AZSDK)" config codeowners generate `
                  --repo-root "$(Build.SourcesDirectory)/${{ repo.RepoName }}" `
                  --package-types mgmt `
                  --section "Management Libraries"

                & "$(AZSDK)" config codeowners generate `
                  --repo-root "$(Build.SourcesDirectory)/${{ repo.RepoName }}" `
                  --package-types client `
                  --package-types compat `
                  --package-types data `
                  --section "Client Libraries"

          - template: /eng/common/pipelines/templates/steps/create-pull-request.yml
            parameters:
              OpenAsDraft: true
              WorkingDirectory: "$(Build.SourcesDirectory)/${{ repo.RepoName }}"
              BaseBranchName: main
              PRBranchName: "$(PRBranchName)"
              PushArgs: '-f'
              PRTitle: '[CODEOWNERS] Automated CODEOWNERS Update'
              PRBody: |
                Updating CODEOWNERS

                This was run in $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)
