trigger: none
pr: none

schedules:
- cron: "0 */4 * * *" # every 4 hours (0-4-8-12-16-20@UTC = 16-20-0-4-8-12@PST = 17-21-1-5-9-13@PDT)
  displayName: 'Scheduled Product Onboarding Issue Processing'
  branches:
    include:
    - main
  always: true

variables:
  - template: /eng/pipelines/templates/variables/image.yml

pool:
  name: $(LINUXPOOL)
  demands: ImageOverride -equals $(LINUXVMIMAGE)

steps:
- template: /eng/common/pipelines/templates/steps/login-to-github.yml
  parameters:
    TokenOwners: 
      - Azure

- template: /eng/common/pipelines/templates/steps/install-azsdk-cli.yml

- task: AzureCLI@2
  displayName: 'Process Product Onboarding Issues (Test)'
  env:
    GH_TOKEN: $(GH_TOKEN)
    AZSDK: $(AZSDK)
  inputs:
    azureSubscription: opensource-api-connection
    scriptType: pscore
    scriptPath: ./eng/scripts/Process-ProductOnboardingIssues.ps1
    scriptArguments: '-IsTest $true'

- task: AzureCLI@2
  displayName: 'Process Product Onboarding Issues'
  env:
    GH_TOKEN: $(GH_TOKEN)
    AZSDK: $(AZSDK)
  inputs:
    azureSubscription: opensource-api-connection
    scriptType: pscore
    scriptPath: ./eng/scripts/Process-ProductOnboardingIssues.ps1
