# Mirror the eng/common folder to all subscribed language repos.
#
# For more information on this file, please see:
# doc/common/common_engsys.md
parameters:
- name: DirectoryToSync
  type: string
  default: eng/common
- name: Repos
  type: object
  default:
    - RepoOwner: Azure
      RepoName: azure-sdk
    - RepoOwner: Azure
      RepoName: azure-sdk-for-cpp
    - RepoOwner: Azure
      RepoName: azure-sdk-for-go
    - RepoOwner: Azure
      RepoName: azure-sdk-for-ios
    - RepoOwner: Azure
      RepoName: azure-sdk-for-java
    - RepoOwner: Azure
      RepoName: azure-sdk-for-js
    - RepoOwner: Azure
      RepoName: azure-sdk-for-net
    - RepoOwner: Azure
      RepoName: azure-sdk-for-python
    - RepoOwner: Azure
      RepoName: azure-sdk-for-rust
    - RepoOwner: Azure
      RepoName: azure-rest-api-specs
    - RepoOwner: Microsoft
      RepoName: mcp
- name: RepoOwners
  type: object
  default:
    - Azure
    - Microsoft

trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - eng/common

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-tool-repo-sync.yml
  parameters:
    DirectoryToSync: ${{ parameters.DirectoryToSync }}
    Repos: ${{ parameters.Repos }}
    RepoOwners: ${{ parameters.RepoOwners }}
