package test

import (
	"context"
	"testing"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-tools/tools/sdk-ai-bots/azure-sdk-qa-bot-backend/config"
	"github.com/Azure/azure-sdk-tools/tools/sdk-ai-bots/azure-sdk-qa-bot-backend/model"
	"github.com/Azure/azure-sdk-tools/tools/sdk-ai-bots/azure-sdk-qa-bot-backend/service/prompt"
	"github.com/Azure/azure-sdk-tools/tools/sdk-ai-bots/azure-sdk-qa-bot-backend/service/search"
	"github.com/stretchr/testify/require"
)

func TestQueryIndex(t *testing.T) {
	config.InitConfiguration()
	config.InitSecrets()
	searchClient := search.NewSearchClient()
	req := &model.QueryIndexRequest{
		Search: "how can i install typespec?",
		Count:  true,
		Top:    5,
		VectorQueries: []model.VectorQuery{
			{
				Text:       "how can i install typespec",
				K:          to.Ptr(5),
				Fields:     "text_vector",
				Kind:       "text",
				Exhaustive: true,
			},
		},
	}
	resp, err := searchClient.QueryIndex(context.Background(), req)
	require.NoError(t, err)
	require.NotNil(t, resp)
	require.Greater(t, len(resp.Value), 0, "Expected at least one search result")
}

func TestGetFullContext(t *testing.T) {
	config.InitConfiguration()
	config.InitSecrets()
	searchClient := search.NewSearchClient()
	resp, err := searchClient.GetCompleteContext(model.Index{
		Title:     "getstarted#installation.md",
		ContextID: "typespec_azure_docs",
	})
	require.NoError(t, err)
	require.NotNil(t, resp)
	require.Greater(t, len(resp), 0, "Expected non-empty context")
}

func TestAgenticSearch(t *testing.T) {
	config.LoadEnvFile()
	config.InitConfiguration()
	config.InitSecrets()
	searchClient := search.NewSearchClient()
	promptParser := prompt.AgenticSearchPromptParser{
		DefaultPromptParser: &prompt.DefaultPromptParser{},
	}
	tenantConfig, _ := config.GetTenantConfig(model.TenantID_AzureSDKOnboarding)
	agenticSearchPrompt, err := promptParser.ParsePrompt(nil, tenantConfig.AgenticSearchPrompt)
	require.NoError(t, err)
	resp, err := searchClient.AgenticSearch(context.Background(), "title: TypeSpec SDK API Reviews Process for Management Plane Services\n\nquestion: Hello General,\nFirst time working on typespec. I'm from Compute team and this is my api-specs PR to add a new preview API version: Add 2025-07-01-preview API version to Azure Fleet by diyellap · Pull Request #36207 · Azure/azure-rest-api-specs.\nIt has autogenerated SDK API reviews. How to get these reviewed by specific SDK teams?", search.AgenticSearchOptions{
		SearchOptions: search.SearchOptions{
			Sources:       tenantConfig.Sources,
			SourceFilter:  tenantConfig.SourceFilter,
			QuestionScope: to.Ptr(model.QuestionScope_Branded),
			ServiceType:   to.Ptr(model.ServiceType_Unknown),
		},
		Prompt: agenticSearchPrompt,
	})
	require.NoError(t, err)
	require.NotNil(t, resp)
	require.Greater(t, len(resp.References), 0, "Expected at least one search result")
}
