### You need to install REST Client extension for your vscode, to run this test

### Remote test (refer to README to get the backend endpoint and access token)
POST https://[backend_endpoint]/completion HTTP/1.1
Content-type: application/json; charset=utf-8
Authorization: Bearer [AccessToken]

{
    "tenant_id": "azure_sdk_qa_bot",
    "message": {
        "role": "user",
        "content": "how to onboard typespec?"
    }
}

### Local test
POST http://localhost:8088/completion HTTP/1.1
Content-type: application/json; charset=utf-8

{
    "tenant_id": "python_channel_qa_bot",
    "message": {
        "role": "user",
        "content": "when could i release mgmt sdk?"
    }
}