package test

import (
	"testing"

	"github.com/Azure/azure-sdk-tools/tools/sdk-ai-bots/azure-sdk-qa-bot-backend/config"
	"github.com/Azure/azure-sdk-tools/tools/sdk-ai-bots/azure-sdk-qa-bot-backend/model"
	"github.com/Azure/azure-sdk-tools/tools/sdk-ai-bots/azure-sdk-qa-bot-backend/service/agent"
	"github.com/stretchr/testify/require"
)

// TestRoutingTenant_General validates routing tenant for all general channel testcases
func TestRoutingTenant_General(t *testing.T) {
	config.LoadEnvFile()
	config.InitConfiguration()
	config.InitSecrets()
	config.InitOpenAIClient()

	service, err := agent.NewCompletionService()
	require.NoError(t, err)

	// Each testcase: query, expected tenant (always model.TenantID_AzureSDKOnboarding for general channel)
	testcases := []struct {
		name    string
		content string
		tenant  model.TenantID
	}{
		{
			"SDK Validation - .NET",
			`I have an open PR inital genome api spec by samira-farhin · Pull Request #25097 · Azure/azure-rest-api-specs-pr that's currently failing on SDK Validation - .NET - PR. My latest changes to resolve SDK Validation in "tspconfig.yaml" are included below. After these updates, the SDK validation issues for Go and Java were resolved, but the C# issue still remains. I'm unsure what else needs to be addressed.\ninital genome api spec by samira-farhin · Pull Request #25097 · Azure/azure-rest-api-specs-pr\ninital genome api spec by samira-farhin · Pull Request #25097 · Azure/azure-rest-api-specs-pr\n\ncommand  pwsh ./eng/scripts/Automation-Sdk-Init.ps1 ../azure-sdk-for-net-pr_tmp/initInput.json ../azure-sdk-for-net-pr_tmp/initOutput.json\ncommand  pwsh ./eng/scripts/Invoke-GenerateAndBuildV2.ps1 ../azure-sdk-for-net-pr_tmp/generateInput.json ../azure-sdk-for-net-pr_tmp/generateOutput.json\ncmdout  [.Net] Start to call tsp-client to generate package:Azure.ResourceManager.Genome\ncmdout  [.Net] Start to build sdk project: /mnt/vss/_work/1/s/azure-sdk-for-net-pr/sdk/genome/Azure.ResourceManager.Genome/src\ncmdout  [.Net] /mnt/vss/_work/1/s/azure-sdk-for-net-pr/sdk/genome/Azure.ResourceManager.Genome/src/Generated/GenomeAccountCollection.cs(270,20): error CS0122: 'GeneratorPageableHelpers' is inaccessible due to its protection level [/mnt/vss/_work/1/s/azure-sdk-for-net-pr/sdk/genome/Azure.ResourceManager.Genome/src/Azure.ResourceManager.Genome.csproj::TargetFramework=netstandard2.0]\n...`,
			model.TenantID_DotnetChannelQaBot,
		},
		{
			"How to Sdk generation in local",
			`I have couple of prs failing with sdk validation. Is there a way to reproduce these errors in local?`,
			model.TenantID_AzureSDKOnboarding,
		},
		{
			"Permission to merge to RPSaaSMaster",
			`Hi\nGeneral\n,\nDue to recent team reorganization I am now in charge of my team and I need to get permission to merge changes to RPSaaSMaster, e.g. I need to merge this PR - Small fix for Dsts Sci Groups by Alessar · Pull Request #24977 · Azure/azure-rest-api-specs-pr\nCould you please help me with that?\nThank you`,
			model.TenantID_AzureSDKOnboarding,
		},
		{
			"MSWB API spec removal",
			`The Azure Modeling and Simulation Workbench (MSWB) preview service has been retired, so I'm trying to remove its related API specs from the REST API specs repository.\nPR Deleting 5 API specs for the deprecated MSWB service - RPSaaSDev by yochu-msft · Pull Request #2508… targets RPSaaSDev to delete 5 API specs.\nI want to move forward with merging this PR without resolving the Swagger LintDiff failure since the specs are being removed.\n'Next Steps to Merge' says "If you still want to proceed merging this PR without addressing the above failures, refer to step 4 in the PR workflow diagram." but 'PR workflow diagram' step 4 loops back that "Follow the instructions in the Next Steps to Merge comment." How should I merge the PR without fixing the failure?\ncc Mick Zaffke`,
			model.TenantID_APISpecReviewBot,
		},
		{
			"Assistance required with breaking change PR",
			`Hi team, We have the following open PR which adds a few missing fields to our returned payload and seems to be marked as a breaking change (violation of rule 1041 - AddedPropertyInResponse). Since we are a REST API only, I'm not sure how counts as a breaking change as it changes nothing about the way existing customers interact with our APIs. Is there some way to suppress this rule/ request an exception?`,
			model.TenantID_APISpecReviewBot,
		},
		{
			"SDK Generation Pipeline - Python codegen from typespec missing required _validation.py file",
			`We used SDK Validation - Python build pipeline to generate our azure-quantum python SDK. The artifacts of the build contains tar of the autogenerated client. However, the required _validation file is entirely missing from the generated client, so generated SDK is broken and invalid. Has anyone seen this before? Are we missing something in our typespec for _validation file to be generated properly?`,
			model.TenantID_PythonChannelQaBot,
		},
		{
			"Java SDK generation failure",
			`I have this pr where java sdk validation is failing, This is the pipeline: https://dev.azure.com/azure-sdk/public/_build/results?buildId=5517681&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=00be4b52-4a63-5865-8e02-c61723ad0692`,
			model.TenantID_JavaChannelQaBot,
		},
		{
			"404 Broken link in PR",
			"For JS - I see that the pipeline run has passed successfully but in the PR we are getting the broken error: [404] broken link https://learn.microsoft.com/javascript/api/@azure/arm-dell-storage. Do you know what's causing this or how to fix it?",
			model.TenantID_JavaScriptChannelQaBot,
		},
	}

	for _, tc := range testcases {
		t.Run(tc.name, func(t *testing.T) {
			messages := []model.Message{{
				Role:    model.Role_User,
				Content: tc.content,
			}}
			llmMessages := convertToLLMMessages(messages)
			routedTenantID, _ := service.RouteTenant(model.TenantID_GeneralQaBot, llmMessages)
			require.NotNil(t, routedTenantID)
			require.Equal(t, tc.tenant, routedTenantID)
		})
	}
}
