parameters:
  - name: DependsOn
    type: object
    default: []
  - name: ArtifactName
    type: string
    default: 'packages'
  - name: Feed
    type: string
    default: 'public/azure-sdk-for-net'
  - name: PublishEnvironment
    type: string
    default: 'none'
  - name: ShouldSign
    type: boolean
    default: true
  - name: ShouldPublish
    type: boolean
    default: true
  - name: ShouldPublishSymbols
    type: boolean
    default: true
  - name: VerifyChangelog
    type: boolean
    default: false
  - name: RequireStrongNames
    type: boolean
    default: true

jobs:
  - job: PrePackagePublish
    displayName: Prepare package for publishing
    dependsOn: ${{ parameters.DependsOn }}
    pool:
      name: $(WINDOWSPOOL)
      image: $(WINDOWSVMIMAGE)
      os: windows

    variables:
    - name: Artifacts
      value: $(Pipeline.Workspace)/${{ parameters.ArtifactName }}
    - name: BuildToolPath
      value: $(Pipeline.Workspace)/_azure-sdk-build-tools

    templateContext:
      outputs:
        - output: pipelineArtifact
          displayName: Upload packages to publish
          condition: succeededOrFailed()
          artifactName: ${{ parameters.ArtifactName }}-signed
          targetPath: $(Artifacts)

    steps:
      - checkout: azure-sdk-build-tools
        path: _azure-sdk-build-tools

      - checkout: self

      - task: AzurePowershell@5
        displayName: 'Request SymWeb and MSDL api publishing'
        inputs:
          pwsh: true
          azureSubscription: 'Azure SDK Symbols Publishing'
          azurePowerShellVersion: 'LatestVersion'
          ScriptType: 'FilePath'
          ScriptPath: $(BuildToolPath)/scripts/symbols/Invoke-SymbolsApiRequest.ps1
          ScriptArguments: >
            -ProjectName 'azure-sdk'
            -RequestName 'azure-sdk-6f5de551'
            -Wait