//go:build go1.16
// +build go1.16

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package test_test

import (
	"context"
	"testing"

	"time"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/internal/recording"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/internal/testutil"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"
	"github.com/stretchr/testify/suite"
)

type SignalrTestSuite struct {
	suite.Suite

	ctx               context.Context
	cred              azcore.TokenCredential
	options           *arm.ClientOptions
	location          string
	resourceGroupName string
	subscriptionId    string
}

func (testsuite *SignalrTestSuite) SetupSuite() {
	testsuite.ctx = context.Background()
	testsuite.cred, testsuite.options = testutil.GetCredAndClientOptions(testsuite.T())
	testsuite.location = testutil.GetEnv("LOCATION", "eastus")
	testsuite.resourceGroupName = testutil.GetEnv("RESOURCE_GROUP_NAME", "")
	testsuite.subscriptionId = testutil.GetEnv("AZURE_SUBSCRIPTION_ID", "")

	testutil.StartRecording(testsuite.T(), "sdk/resourcemanager//test/testdata")
	resourceGroup, _, err := testutil.CreateResourceGroup(testsuite.ctx, testsuite.subscriptionId, testsuite.cred, testsuite.options, testsuite.location)
	testsuite.Require().NoError(err)
	testsuite.resourceGroupName = *resourceGroup.Name
}

func (testsuite *SignalrTestSuite) TearDownSuite() {
	_, err := testutil.DeleteResourceGroup(testsuite.ctx, testsuite.subscriptionId, testsuite.cred, testsuite.options, testsuite.resourceGroupName)
	testsuite.Require().NoError(err)
	testutil.StopRecording(testsuite.T())
}

func TestSignalrTestSuite(t *testing.T) {
	suite.Run(t, new(SignalrTestSuite))
}

func (testsuite *SignalrTestSuite) TestSignalr() {
	var resourceName string
	var err error
	// From step Generate_Unique_Name
	template := map[string]interface{}{
		"$schema":        "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
		"contentVersion": "1.0.0.0",
		"outputs": map[string]interface{}{
			"resourceName": map[string]interface{}{
				"type":  "string",
				"value": "[variables('name').value]",
			},
		},
		"resources": []interface{}{},
		"variables": map[string]interface{}{
			"name": map[string]interface{}{
				"type": "string",
				"metadata": map[string]interface{}{
					"description": "Name of the SignalR service.",
				},
				"value": "[concat('sw',uniqueString(resourceGroup().id))]",
			},
		},
	}
	params := map[string]interface{}{}
	deployment := armresources.Deployment{
		Properties: &armresources.DeploymentProperties{
			Template:   template,
			Parameters: params,
			Mode:       armresources.DeploymentModeIncremental.ToPtr(),
		},
	}
	deploymentExtend, err := testutil.CreateDeployment(testsuite.ctx, testsuite.subscriptionId, testsuite.cred, testsuite.options, testsuite.resourceGroupName, "Generate_Unique_Name", &deployment)
	testsuite.Require().NoError(err)
	resourceName = deploymentExtend.Properties.Outputs["resourceName"].(map[string]interface{})["value"].(string)

	// From step SignalR_CheckNameAvailability
	signalRClient := test.NewSignalRClient(testsuite.subscriptionId, testsuite.cred, testsuite.options)
	_, err = signalRClient.CheckNameAvailability(testsuite.ctx,
		testsuite.location,
		test.NameAvailabilityParameters{
			Name: to.StringPtr(resourceName),
			Type: to.StringPtr("Microsoft.SignalRService/SignalR"),
		},
		nil)
	testsuite.Require().NoError(err)

	// From step SignalR_CreateOrUpdate
	signalRClientCreateOrUpdatePollerResponse, err := signalRClient.BeginCreateOrUpdate(testsuite.ctx,
		testsuite.resourceGroupName,
		resourceName,
		test.ResourceInfo{
			Location: to.StringPtr(testsuite.location),
			Tags: map[string]*string{
				"key1": to.StringPtr("value1"),
			},
			Identity: &test.ManagedIdentity{
				Type: test.ManagedIdentityTypeSystemAssigned.ToPtr(),
			},
			Kind: test.ServiceKindSignalR.ToPtr(),
			Properties: &test.SignalRProperties{
				Cors: &test.SignalRCorsSettings{
					AllowedOrigins: []*string{
						to.StringPtr("https://foo.com"),
						to.StringPtr("https://bar.com")},
				},
				DisableAADAuth:   to.BoolPtr(false),
				DisableLocalAuth: to.BoolPtr(false),
				Features: []*test.SignalRFeature{
					{
						Flag:       test.FeatureFlagsServiceMode.ToPtr(),
						Properties: map[string]*string{},
						Value:      to.StringPtr("Serverless"),
					},
					{
						Flag:       test.FeatureFlagsEnableConnectivityLogs.ToPtr(),
						Properties: map[string]*string{},
						Value:      to.StringPtr("True"),
					},
					{
						Flag:       test.FeatureFlagsEnableMessagingLogs.ToPtr(),
						Properties: map[string]*string{},
						Value:      to.StringPtr("False"),
					},
					{
						Flag:       test.FeatureFlagsEnableLiveTrace.ToPtr(),
						Properties: map[string]*string{},
						Value:      to.StringPtr("False"),
					}},
				NetworkACLs: &test.SignalRNetworkACLs{
					DefaultAction: test.ACLActionDeny.ToPtr(),
					PrivateEndpoints: []*test.PrivateEndpointACL{
						{
							Allow: []*test.SignalRRequestType{
								test.SignalRRequestTypeServerConnection.ToPtr()},
							Name: to.StringPtr(resourceName + ".1fa229cd-bf3f-47f0-8c49-afb36723997e"),
						}},
					PublicNetwork: &test.NetworkACL{
						Allow: []*test.SignalRRequestType{
							test.SignalRRequestTypeClientConnection.ToPtr()},
					},
				},
				PublicNetworkAccess: to.StringPtr("Enabled"),
				TLS: &test.SignalRTLSSettings{
					ClientCertEnabled: to.BoolPtr(false),
				},
				Upstream: &test.ServerlessUpstreamSettings{
					Templates: []*test.UpstreamTemplate{
						{
							Auth: &test.UpstreamAuthSettings{
								Type: test.UpstreamAuthTypeManagedIdentity.ToPtr(),
								ManagedIdentity: &test.ManagedIdentitySettings{
									Resource: to.StringPtr("api://example"),
								},
							},
							CategoryPattern: to.StringPtr("*"),
							EventPattern:    to.StringPtr("connect,disconnect"),
							HubPattern:      to.StringPtr("*"),
							URLTemplate:     to.StringPtr("https://example.com/chat/api/connect"),
						}},
				},
			},
			SKU: &test.ResourceSKU{
				Name:     to.StringPtr("Standard_S1"),
				Capacity: to.Int32Ptr(1),
				Tier:     test.SignalRSKUTierStandard.ToPtr(),
			},
		},
		nil)
	testsuite.Require().NoError(err)
	if recording.GetRecordMode() == recording.PlaybackMode {
		for {
			_, err = signalRClientCreateOrUpdatePollerResponse.Poller.Poll(testsuite.ctx)
			testsuite.Require().NoError(err)
			if signalRClientCreateOrUpdatePollerResponse.Poller.Done() {
				_, err = signalRClientCreateOrUpdatePollerResponse.Poller.FinalResponse(testsuite.ctx)
				testsuite.Require().NoError(err)
				break
			}
		}
	} else {
		_, err = signalRClientCreateOrUpdatePollerResponse.PollUntilDone(testsuite.ctx, 10*time.Second)
		testsuite.Require().NoError(err)
	}

	// From step SignalR_Get
	_, err = signalRClient.Get(testsuite.ctx,
		testsuite.resourceGroupName,
		resourceName,
		nil)
	testsuite.Require().NoError(err)

	// From step SignalR_Update
	signalRClientUpdatePollerResponse, err := signalRClient.BeginUpdate(testsuite.ctx,
		testsuite.resourceGroupName,
		resourceName,
		test.ResourceInfo{
			Location: to.StringPtr(testsuite.location),
			Tags: map[string]*string{
				"key1": to.StringPtr("value1"),
			},
			Identity: &test.ManagedIdentity{
				Type: test.ManagedIdentityTypeSystemAssigned.ToPtr(),
			},
			Kind: test.ServiceKindSignalR.ToPtr(),
			Properties: &test.SignalRProperties{
				Cors: &test.SignalRCorsSettings{
					AllowedOrigins: []*string{
						to.StringPtr("https://foo.com"),
						to.StringPtr("https://bar.com")},
				},
				DisableAADAuth:   to.BoolPtr(false),
				DisableLocalAuth: to.BoolPtr(false),
				Features: []*test.SignalRFeature{
					{
						Flag:       test.FeatureFlagsServiceMode.ToPtr(),
						Properties: map[string]*string{},
						Value:      to.StringPtr("Serverless"),
					},
					{
						Flag:       test.FeatureFlagsEnableConnectivityLogs.ToPtr(),
						Properties: map[string]*string{},
						Value:      to.StringPtr("True"),
					},
					{
						Flag:       test.FeatureFlagsEnableMessagingLogs.ToPtr(),
						Properties: map[string]*string{},
						Value:      to.StringPtr("False"),
					},
					{
						Flag:       test.FeatureFlagsEnableLiveTrace.ToPtr(),
						Properties: map[string]*string{},
						Value:      to.StringPtr("False"),
					}},
				NetworkACLs: &test.SignalRNetworkACLs{
					DefaultAction: test.ACLActionDeny.ToPtr(),
					PrivateEndpoints: []*test.PrivateEndpointACL{
						{
							Allow: []*test.SignalRRequestType{
								test.SignalRRequestTypeServerConnection.ToPtr()},
							Name: to.StringPtr(resourceName + ".1fa229cd-bf3f-47f0-8c49-afb36723997e"),
						}},
					PublicNetwork: &test.NetworkACL{
						Allow: []*test.SignalRRequestType{
							test.SignalRRequestTypeClientConnection.ToPtr()},
					},
				},
				PublicNetworkAccess: to.StringPtr("Enabled"),
				TLS: &test.SignalRTLSSettings{
					ClientCertEnabled: to.BoolPtr(false),
				},
				Upstream: &test.ServerlessUpstreamSettings{
					Templates: []*test.UpstreamTemplate{
						{
							Auth: &test.UpstreamAuthSettings{
								Type: test.UpstreamAuthTypeManagedIdentity.ToPtr(),
								ManagedIdentity: &test.ManagedIdentitySettings{
									Resource: to.StringPtr("api://example"),
								},
							},
							CategoryPattern: to.StringPtr("*"),
							EventPattern:    to.StringPtr("connect,disconnect"),
							HubPattern:      to.StringPtr("*"),
							URLTemplate:     to.StringPtr("https://example.com/chat/api/connect"),
						}},
				},
			},
			SKU: &test.ResourceSKU{
				Name:     to.StringPtr("Standard_S1"),
				Capacity: to.Int32Ptr(1),
				Tier:     test.SignalRSKUTierStandard.ToPtr(),
			},
		},
		nil)
	testsuite.Require().NoError(err)
	if recording.GetRecordMode() == recording.PlaybackMode {
		for {
			_, err = signalRClientUpdatePollerResponse.Poller.Poll(testsuite.ctx)
			testsuite.Require().NoError(err)
			if signalRClientUpdatePollerResponse.Poller.Done() {
				_, err = signalRClientUpdatePollerResponse.Poller.FinalResponse(testsuite.ctx)
				testsuite.Require().NoError(err)
				break
			}
		}
	} else {
		_, err = signalRClientUpdatePollerResponse.PollUntilDone(testsuite.ctx, 10*time.Second)
		testsuite.Require().NoError(err)
	}

	// From step SignalR_ListKeys
	_, err = signalRClient.ListKeys(testsuite.ctx,
		testsuite.resourceGroupName,
		resourceName,
		nil)
	testsuite.Require().NoError(err)

	// From step SignalR_RegenerateKey
	signalRClientRegenerateKeyPollerResponse, err := signalRClient.BeginRegenerateKey(testsuite.ctx,
		testsuite.resourceGroupName,
		resourceName,
		test.RegenerateKeyParameters{
			KeyType: test.KeyTypePrimary.ToPtr(),
		},
		nil)
	testsuite.Require().NoError(err)
	if recording.GetRecordMode() == recording.PlaybackMode {
		for {
			_, err = signalRClientRegenerateKeyPollerResponse.Poller.Poll(testsuite.ctx)
			testsuite.Require().NoError(err)
			if signalRClientRegenerateKeyPollerResponse.Poller.Done() {
				_, err = signalRClientRegenerateKeyPollerResponse.Poller.FinalResponse(testsuite.ctx)
				testsuite.Require().NoError(err)
				break
			}
		}
	} else {
		_, err = signalRClientRegenerateKeyPollerResponse.PollUntilDone(testsuite.ctx, 10*time.Second)
		testsuite.Require().NoError(err)
	}

	// From step SignalR_Restart
	signalRClientRestartPollerResponse, err := signalRClient.BeginRestart(testsuite.ctx,
		testsuite.resourceGroupName,
		resourceName,
		nil)
	testsuite.Require().NoError(err)
	if recording.GetRecordMode() == recording.PlaybackMode {
		for {
			_, err = signalRClientRestartPollerResponse.Poller.Poll(testsuite.ctx)
			testsuite.Require().NoError(err)
			if signalRClientRestartPollerResponse.Poller.Done() {
				_, err = signalRClientRestartPollerResponse.Poller.FinalResponse(testsuite.ctx)
				testsuite.Require().NoError(err)
				break
			}
		}
	} else {
		_, err = signalRClientRestartPollerResponse.PollUntilDone(testsuite.ctx, 10*time.Second)
		testsuite.Require().NoError(err)
	}

	// From step Usages_List
	usagesClient := test.NewUsagesClient(testsuite.subscriptionId, testsuite.cred, testsuite.options)
	usagesClientListPager := usagesClient.List(testsuite.location,
		nil)
	for usagesClientListPager.NextPage(testsuite.ctx) {
		err = usagesClientListPager.Err()
		testsuite.Require().NoError(err)
		for _, v := range usagesClientListPager.PageResponse().Value {
			_ = v
		}
	}

	// From step SignalR_ListByResourceGroup
	signalRClientListByResourceGroupPager := signalRClient.ListByResourceGroup(testsuite.resourceGroupName,
		nil)
	for signalRClientListByResourceGroupPager.NextPage(testsuite.ctx) {
		err = signalRClientListByResourceGroupPager.Err()
		testsuite.Require().NoError(err)
		for _, v := range signalRClientListByResourceGroupPager.PageResponse().Value {
			_ = v
		}
	}

	// From step SignalR_ListBySubscription
	signalRClientListBySubscriptionPager := signalRClient.ListBySubscription(nil)
	for signalRClientListBySubscriptionPager.NextPage(testsuite.ctx) {
		err = signalRClientListBySubscriptionPager.Err()
		testsuite.Require().NoError(err)
		for _, v := range signalRClientListBySubscriptionPager.PageResponse().Value {
			_ = v
		}
	}

	// From step Operations_List
	operationsClient := test.NewOperationsClient(testsuite.cred, testsuite.options)
	operationsClientListPager := operationsClient.List(nil)
	for operationsClientListPager.NextPage(testsuite.ctx) {
		err = operationsClientListPager.Err()
		testsuite.Require().NoError(err)
		for _, v := range operationsClientListPager.PageResponse().Value {
			_ = v
		}
	}

	// From step SignalR_Delete
	signalRClientDeletePollerResponse, err := signalRClient.BeginDelete(testsuite.ctx,
		testsuite.resourceGroupName,
		resourceName,
		nil)
	testsuite.Require().NoError(err)
	if recording.GetRecordMode() == recording.PlaybackMode {
		for {
			_, err = signalRClientDeletePollerResponse.Poller.Poll(testsuite.ctx)
			testsuite.Require().NoError(err)
			if signalRClientDeletePollerResponse.Poller.Done() {
				_, err = signalRClientDeletePollerResponse.Poller.FinalResponse(testsuite.ctx)
				testsuite.Require().NoError(err)
				break
			}
		}
	} else {
		_, err = signalRClientDeletePollerResponse.PollUntilDone(testsuite.ctx, 10*time.Second)
		testsuite.Require().NoError(err)
	}
}
