export { dotnet as csharp } from './langSpecs/langs/dotnet';
export { go } from './langSpecs/langs/go';
export { java } from './langSpecs/langs/java';
export { javascript } from './langSpecs/langs/javascript';
export * from './langSpecs/languageConfiguration';
export { python } from './langSpecs/langs/python';
export * from './sdkAutomation';
export * from './specificationPREvent';
export { ruby } from './langSpecs/langs/ruby';
export { cli } from './langSpecs/langs/cli';
export { trenton } from './langSpecs/langs/trenton';
export { azureresourceschema } from './langSpecs/langs/azureresourceschema';
