import { describe, expect, test } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { mapReleasePlan, LANGUAGES } from "../lib/devops-api.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const appJs = readFileSync(path.join(__dirname, "../public/app.js"), "utf8");
const indexHtml = readFileSync(
  path.join(__dirname, "../public/index.html"),
  "utf8",
);
const styleCss = readFileSync(
  path.join(__dirname, "../public/style.css"),
  "utf8",
);

describe("Action required is restricted to service team", () => {
  test("does not render the SDK PRs Under Review guidance", () => {
    expect(appJs).not.toContain("SDK PRs Under Review");
  });

  test("does not push SDK PR Reviewer into the action-from list", () => {
    expect(appJs).not.toContain('actionFrom.push("SDK PR Reviewer")');
  });

  test("tile action badge is gated to service team actions", () => {
    expect(appJs).toContain("isServiceTeamAction(step.action)");
    expect(appJs).toContain("function isServiceTeamAction(action)");
  });
});

describe("Generated by automation tag", () => {
  test("badge is rendered when created using Automation", () => {
    expect(appJs).toContain("isGeneratedByAutomationPlan");
    expect(appJs).toContain("badge-generated-by-automation");
    expect(appJs).toContain('=== "automation"');
  });

  test("tag is available as a global filter option", () => {
    expect(indexHtml).toContain('value="generated-by-automation"');
    expect(appJs).toContain('tagFilter === "generated-by-automation"');
  });

  test("badge CSS class is defined", () => {
    expect(styleCss).toContain(".badge-generated-by-automation");
  });
});

describe("Language filter", () => {
  test("language filter dropdown exists in release plan tab", () => {
    expect(indexHtml).toContain('id="global-language-filter"');
    expect(indexHtml).toContain("$store.app.filters.language");
  });

  test("plan is narrowed to selected language for display", () => {
    expect(appJs).toContain("function narrowPlanToLanguage(p, lang)");
    expect(appJs).toContain("function displayPlan(p)");
    expect(appJs).toContain("p = displayPlan(p);");
  });

  test("language filter combines with tag filter", () => {
    expect(appJs).toContain(
      "const pt = langFilter ? narrowPlanToLanguage(p, langFilter) : p;",
    );
  });

  test("language filter change triggers re-render", () => {
    expect(appJs).toContain("store().filters.language,");
  });
});

describe("SDK generation status in PR status column", () => {
  test("shows generation pipeline link when generation failed and no PR", () => {
    expect(appJs).toContain("failed to generate sdk.");
    expect(appJs).toContain("sdkGenerationPipeline");
    expect(appJs).toContain("View pipeline");
  });
});

describe("Release approval required", () => {
  test("badge, tag filter, and action guidance exist", () => {
    expect(appJs).toContain("isReleaseApprovalRequiredPlan");
    expect(appJs).toContain("badge-release-approval-required");
    expect(indexHtml).toContain('value="release-approval-required"');
    expect(appJs).toContain(
      "Approve the package release using release pipeline",
    );
  });

  test("approval pending shows an Approve Release action linking to the pipeline", () => {
    expect(appJs).toContain('=== "approval pending"');
    expect(appJs).toContain('relSt === "approval pending" && l.releasePipeline');
    expect(appJs).toContain("Approve Release");
    expect(appJs).toContain("l.releasePipeline");
  });

  test("approval pending shows a prominent Pending Release Approval badge", () => {
    expect(appJs).toContain("release-approval-pending-badge");
    expect(appJs).toContain("Pending Release Approval");
    expect(styleCss).toContain(".release-approval-pending-badge");
    expect(styleCss).toContain(".action-btn-approve");
  });

  test("release approval badge CSS class is defined", () => {
    expect(styleCss).toContain(".badge-release-approval-required");
  });
});

describe("mapReleasePlan pipeline fields", () => {
  test("maps SDK generation and release pipelines per language", () => {
    const fields = {
      "System.Title": "Pipeline Test",
      "System.State": "In Progress",
    };
    for (const lang of LANGUAGES) {
      fields[`Custom.SDKGenerationPipelineFor${lang}`] =
        `https://dev.azure.com/gen/${lang}`;
      fields[`Custom.ReleasePipelineFor${lang}`] =
        `https://dev.azure.com/rel/${lang}`;
    }
    const wi = { id: 950, fields, relations: [] };
    const result = mapReleasePlan(wi, {});

    expect(result.languages[".NET"].sdkGenerationPipeline).toBe(
      "https://dev.azure.com/gen/Dotnet",
    );
    expect(result.languages[".NET"].releasePipeline).toBe(
      "https://dev.azure.com/rel/Dotnet",
    );
    expect(result.languages["Python"].releasePipeline).toBe(
      "https://dev.azure.com/rel/Python",
    );
  });

  test("pipeline fields default to empty string when missing", () => {
    const wi = {
      id: 951,
      fields: { "System.Title": "No Pipelines", "System.State": "New" },
      relations: [],
    };
    const result = mapReleasePlan(wi, {});
    expect(result.languages[".NET"].sdkGenerationPipeline).toBe("");
    expect(result.languages[".NET"].releasePipeline).toBe("");
  });
});

describe("Action required never attributes to Service Partner Team", () => {
  test("Service Partner Team is not pushed as an action owner", () => {
    expect(appJs).not.toContain('actionFrom.push("Service Partner Team")');
    expect(appJs).not.toContain("Service Partner Team");
  });
});

describe("Automation submitter is not shown as action owner", () => {
  test("serviceTeamLabel omits the automation account name", () => {
    expect(appJs).toContain("function serviceTeamLabel(submittedBy)");
    expect(appJs).toContain("function isAutomationSubmitter(submittedBy)");
    expect(appJs).toContain('"azure-sdk-1es-open-source-assistant"');
  });

  test("all service team labels use the helper (no inline submitter suffix)", () => {
    // The raw inline "Service Team (${p.submittedBy})" pattern must be gone so
    // the automation account name is never surfaced as an action owner.
    expect(appJs).not.toContain("`Service Team (${p.submittedBy})`");
  });
});

describe("Failed to generate SDK tag", () => {
  test("tag filter option and logic exist", () => {
    expect(indexHtml).toContain('value="sdk-generation-failed"');
    expect(appJs).toContain('tagFilter === "sdk-generation-failed"');
    expect(appJs).toContain("function isSdkGenerationFailedPlan(p)");
  });
});

describe("Empty plane groups are hidden when filtering", () => {
  test("filtering flag includes tag and language filters", () => {
    expect(appJs).toContain(
      "filter ||\n      singlePlan ||\n      monthFilter ||\n      tagFilter ||\n      langFilter",
    );
  });

  test("plane column is hidden when filtering yields no plans for that plane", () => {
    expect(appJs).toContain(
      'planeFilter === "data" || (isFiltering && mgmt.length === 0)',
    );
    expect(appJs).toContain(
      'planeFilter === "mgmt" || (isFiltering && data.length === 0)',
    );
  });
});
