### You need to install REST Client extension for your vscode, to run this test

### Local test - chat
POST http://localhost:8080/agent/chat HTTP/1.1
Content-type: application/json; charset=utf-8

{
    "tenant_id": "typespec_channel_qa_bot",
    "message": {
            "role": "user",
            "content": "hi",
            "user_id": "test_user_id",
            "user_name": "test_user_name"
    },
    "conversation_id": "test_conversation_id",
    "conversation_type": "teams_channel"
}

### Local test - feedback
POST http://localhost:8080/agent/feedback HTTP/1.1
Content-type: application/json; charset=utf-8

{
    "tenant_id": "typespec_channel_qa_bot",
    "conversation_id": "test_conversation_id",
    "reaction": "good",
    "comment": "Great response!",
    "reasons": ["Accurate", "Helpful"]
}

### Local test - intention
POST http://localhost:8080/message/intention HTTP/1.1
Content-type: application/json; charset=utf-8

{
    "message": {
            "role": "user",
            "content": "test message",
            "user_id": "test_user_id",
            "user_name": "test_user_name"
    },
    "conversation_id": "test_conversation_id",
    "conversation_type": "teams_channel"
}