namespace Azure.Sdk.Tools.Assets.MaintenanceTool.Model
{
    /// <summary>
    /// This class represents a single reference TO the assets repo FROM a language repo. It is populated by combining
    /// an assets's json content with metadata about which language repo it was discovered in.
    ///
    /// The "language" repo is the repo from which recordings are being generated. The "assets" repo is the storage medium for a set
    /// of recordings that are generated by invoking tests in record mode FROM the language repo.
    /// </summary>
    public class AssetsResult
    {
        public AssetsResult(string repo, string repoCommit, string assetsLocation, string tag, string tagRepo, string? backupUri = null, DateTime? scanDate = null)
        {
            LanguageRepo = repo;
            Commit = repoCommit;
            AssetsLocation = assetsLocation;
            Tag = tag;
            AssetsRepo = tagRepo;
            BackupUri = backupUri;
            CreationDate = scanDate??DateTime.UtcNow;
        }

        public AssetsResult()
        {
            LanguageRepo = string.Empty;
            Commit = string.Empty;
            AssetsLocation = string.Empty;
            Tag = string.Empty;
            AssetsRepo = string.Empty;
            BackupUri = string.Empty;
            CreationDate = DateTime.UtcNow;
        }

        /// <summary>
        /// The containing language repo from within which this result was generated.
        /// </summary>
        public string LanguageRepo { get; set; }

        /// <summary>
        /// The SHA of the language repo from which this result was generated.
        /// </summary>
        public string Commit { get; set; }

        /// <summary>
        /// The location of the assets.json within the language repo from which this result was generated.
        /// </summary>
        public string AssetsLocation { get; set; }

        /// <summary>
        /// What tag in the assets repo is this reference pointed at?
        /// </summary>
        public string Tag { get; set; }

        /// <summary>
        /// Which git repo is being used to store the assets? In other words, the targeted assets repo.
        /// </summary>
        public string AssetsRepo { get; set; }

        /// <summary>
        /// The URI of where we backed this item up. Null when we haven't yet backed up this instance.
        /// </summary>
        public string? BackupUri { get; set; }

        /// <summary>
        /// Used as a datapoint for debugging and testing of the scanner. Creation datetime of this result.
        /// </summary>
        public DateTime CreationDate { get; set; }
    }
}
