name: eng/common/tsp-client - Tests

on:
  pull_request:
    paths:
      - .github/workflows/eng-common-tsp-client-tests.yml
      - eng/common/tsp-client/**

permissions:
  contents: read

jobs:
  eng-common-tsp-client-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: eng/common-tests/tsp-client

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github
            eng/common/tsp-client

      - name: Use Node 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - run: npm ci

      - name: npm ls -a

      - run: npm run lint

      - run: npm run format:check:ci

      - run: npm run test:ci
