name: eng/common/tsp-client - Tests

on:
  pull_request:
    paths:
      - .github/workflows/eng-common-tsp-client-tests.yml
      - eng/common/tsp-client/**
      - eng/common-tests/tsp-client/**

permissions:
  contents: read

jobs:
  eng-common-tsp-client-tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-slim

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: tools/eng/common-tests/tsp-client

    steps:
      - name: Checkout self
        uses: actions/checkout@v6
        with:
          path: tools
          sparse-checkout: |
            .github
            eng/common/tsp-client
            eng/common-tests/tsp-client

      - name: Checkout js
        uses: actions/checkout@v6
        with:
          repository: Azure/azure-sdk-for-js
          path: js
          sparse-checkout: |
            eng
            sdk/template

      # - name: Setup node
      #   uses: actions/setup-node@v6
      #   with:
      #     cache: "npm"
      #     cache-dependency-path: tools/eng/common-tests/tsp-client/package-lock.json

      # - run: npm ci --no-audit --no-fund --prefer-offline

      # - run: npm ls -a

      # - run: npm run lint

      # - run: npm run format:check:ci

      # - run: npm run test:ci

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          cache: "npm"
          cache-dependency-path: tools/eng/common/tsp-client/package-lock.json

      - run: npm ci --no-audit --no-fund --prefer-offline
        working-directory: tools/eng/common/tsp-client

      - name: "[js] tsp-client update"
        run: |
          npm exec \
            --prefix "${{ github.workspace }}/tools/eng/common/tsp-client" \
            --no -- \
            tsp-client update
        working-directory: js/sdk/template/template
