name: eng/common/tsp-client - test

on:
  pull_request:
    paths:
      - .github/workflows/eng-common-tsp-client-tests.yml
      - eng/common/tsp-client/**
      - eng/common-tests/tsp-client/**

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v6
        with:
          path: tools
          sparse-checkout: |
            .github
            eng/common/tsp-client
            eng/common-tests/tsp-client

      - name: Checkout js
        uses: actions/checkout@v6
        with:
          repository: Azure/azure-sdk-for-js
          path: js
          sparse-checkout: |
            eng
            sdk/template

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          cache: "npm"
          cache-dependency-path: |
            tools/eng/common/tsp-client/package-lock.json
            tools/eng/common-tests/tsp-client/package-lock.json

      - name: Install deps for tools/eng/common/tsp-client
        run: |
          echo "::group::npm ci"
          npm ci --no-audit --no-fund --prefer-offline
          echo "::endgroup::"
          echo "::group::npm ls -a"
          npm ls -a || true
          echo "::endgroup::"
        working-directory: tools/eng/common/tsp-client

      - name: Install deps for tools/eng/common-tests/tsp-client
        run: |
          echo "::group::npm ci"
          npm ci --no-audit --no-fund --prefer-offline
          echo "::endgroup::"
          echo "::group::npm ls -a"
          npm ls -a || true
          echo "::endgroup::"
        working-directory: tools/eng/common-tests/tsp-client

      - run: npm run lint
        working-directory: tools/eng/common-tests/tsp-client

      - run: npm run format:check:ci
        working-directory: tools/eng/common-tests/tsp-client

      - run: npm run test:ci
        working-directory: tools/eng/common-tests/tsp-client

      # TODO: migrate test from bash to vitest
      - name: "[js] tsp-client update"
        run: |
          npm exec \
            --prefix "${{ github.workspace }}/tools/eng/common/tsp-client" \
            --no -- \
            tsp-client update
        working-directory: js/sdk/template/template
