name: eng/common/tsp-client - Tests

on:
  pull_request:
    paths:
      - .github/workflows/eng-common-tsp-client-tests.yml
      - eng/common/tsp-client/**
      - eng/common-tests/tsp-client/**

permissions:
  contents: read

jobs:
  eng-common-tsp-client-tests:
    runs-on: ubuntu-slim

    defaults:
      run:
        working-directory: eng/common-tests/tsp-client

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github
            eng/common/tsp-client
            eng/common-tests/tsp-client

      - uses: actions/setup-node@v6
        cache: "npm"
        cache-dependency-path: eng/common-tests/tsp-client/package-lock.json

      - run: npm ci --no-audit --no-fund

      - run: npm ls -a

      - run: npm run lint

      - run: npm run format:check:ci

      - run: npm run test:ci
