name: tsp-client - Test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/tsp-client-tests.yml
      - tools/tsp-client/**
  pull_request:
    paths:
      - .github/workflows/tsp-client-tests.yml
      - tools/tsp-client/**

jobs:
  tsp-client:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node-version: 20
          - os: windows-latest
            node-version: 24

    runs-on: ${{ matrix.os }}

    steps:
      - if: runner.os == 'Windows'
        run: git config --global core.longpaths true
        shell: pwsh

      # SHA corresponds to actions/checkout@v6
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          sparse-checkout: |
            .github/workflows
            tools/tsp-client

      - name: Use Node ${{ matrix.node-version }}.x
        # SHA corresponds to actions/setup-node@v6
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: ${{ matrix.node-version }}.x

      - run: npm ci
        shell: pwsh
        working-directory: tools/tsp-client

      - run: npm ls -a
        shell: pwsh
        continue-on-error: true
        working-directory: tools/tsp-client

      - run: npm run build
        shell: pwsh
        working-directory: tools/tsp-client

      - run: npm run test
        shell: pwsh
        working-directory: tools/tsp-client
      
      - run: npm run format:check
        shell: pwsh
        working-directory: tools/tsp-client
