import { ApiVersionType } from "../../common/types.js";
import { IApiVersionTypeExtractor, IModelOnlyChecker } from "../../common/interfaces.js";
import { getApiVersionTypeFromRestClient, tryFindRestClientPath, getApiVersionTypeFromNpm, getApiVersionTypeFromMetadata } from "../../xlc/apiVersion/utils.js";
import { logger } from "../../utils/logger.js";
import { getNpmPackageName } from "../../common/utils.js";
import { isBetaVersion } from "../../utils/version.js";
import { checkDirectoryExistsInGithub } from "../../common/npmUtils.js";
import { tryGetNpmView } from "../../common/npmUtils.js";
import { getLatestStableVersion } from "../../utils/version.js";

export const getApiVersionType: IApiVersionTypeExtractor = async (
    packageRoot: string,
    apiVersion?: string
): Promise<ApiVersionType> => {
    if (apiVersion) {
        return isBetaVersion(apiVersion) ? ApiVersionType.Preview : ApiVersionType.Stable;
    }

    // Try reading from metadata.json (generated by codegen for Azure flavor packages)
    // Check this first as it's the primary source for API version information
    logger.info('Trying to get api version from metadata.json');
    const typeFromMetadata = await getApiVersionTypeFromMetadata(packageRoot);
    if (typeFromMetadata !== ApiVersionType.None) {
        return typeFromMetadata;
    }

    // NOTE: when there's customized code, emitter must put generated code in root/generated folder
    const clientPatterns = ["src/api/*Context.ts", "src/rest/*Client.ts"];
    for (const pattern of clientPatterns) {
        const typeFromClient = await getApiVersionTypeFromRestClient(packageRoot, pattern, tryFindRestClientPath);
        if (typeFromClient !== ApiVersionType.None) return typeFromClient;
    }

    const isModelOnlyPackage = await isModelOnly(packageRoot);
    if (isModelOnlyPackage) {
        const packageName = getNpmPackageName(packageRoot);
        return await getApiVersionTypeFromNpm(packageName);
    }

    // Default to None if no version information found
    logger.warn(`Failed to determine API version type for ${packageRoot}, returning None`);
    return ApiVersionType.None;
};

export const isModelOnly: IModelOnlyChecker = async (packageRoot: string): Promise<boolean> => {
    // Get npm view to find the latest stable version
    const packageName = getNpmPackageName(packageRoot);
    const npmViewResult = await tryGetNpmView(packageName);
    if (!npmViewResult) {
        logger.warn(`No npm package found for ${packageName}, cannot check GitHub directory`);
        return true;
    }

    const stableVersion = getLatestStableVersion(npmViewResult);
    if (!stableVersion) {
        logger.warn(`No stable version found for ${packageName}, cannot check GitHub directory`);
        return true;
    }

    // Check if src/api exists in the GitHub repository
    const hasOperationsInGithub = await checkDirectoryExistsInGithub(
        packageRoot,
        ["src/api", "src/operations"],
        packageName,
        stableVersion
    );

    if (!hasOperationsInGithub) {
        logger.warn(`Neither "src/api" nor "src/operations" found in GitHub for ${packageName}; treating as a model-only service.`);
        return true;
    }

    logger.info(`Found one of "src/api" / "src/operations" in GitHub for ${packageRoot}; this is not a model-only service.`);
    return false;
};
