parameters:
- name: ToolName
- name: ServiceProject
- name: TestProject
- name: Production
  type: object
  default: {}
- name: Staging
  type: object
  default: {}

stages:
    - stage: Build
      variables:
      - template: ../variables/globals.yml
      jobs:
      - job: BuildPackage
        pool:
          name: azsdk-pool-mms-ubuntu-2204-general
          vmImage: ubuntu-22.04
        steps:
          - template: /eng/pipelines/templates/steps/install-dotnet.yml
          - pwsh: |
              dotnet build tools/${{ parameters.ToolName }} --configuration Release
            displayName: Build
          - pwsh: |
              dotnet test tools/${{ parameters.ToolName }}/${{ parameters.TestProject }} --configuration Release
            displayName: Test
          - pwsh: |
              dotnet publish tools/${{ parameters.ToolName }}/${{ parameters.ServiceProject }} --configuration Release --output $(Build.ArtifactStagingDirectory)/app
            displayName: Publish
          - task: ArchiveFiles@2
            displayName: Archive
            inputs:
              rootFolderOrFile: $(Build.ArtifactStagingDirectory)/app
              includeRootFolder: false
              archiveFile: $(Build.ArtifactStagingDirectory)/${{ parameters.ToolName }}-$(Build.BuildID).zip
          - task: AzureWebApp@1
            displayName: Deploy
            inputs:
              azureSubscription: ${{ parameters.Staging.AzureSubscription }}
              resourceGroupName: ${{ parameters.Staging.ResourceGroupName }}
              appName: ${{ parameters.Staging.ResourceName }}
              package: $(Build.ArtifactStagingDirectory)/${{ parameters.ToolName }}-$(Build.BuildID).zip
          - publish: $(Build.ArtifactStagingDirectory)
            displayName: Upload
            artifact: artifacts
            condition: succeededOrFailed()